-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [ed25519_hss]: function definitions
import Aeneas
import Ed25519Hss.Types
import Ed25519Hss.FunsExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace ed25519_hss

/-- [ed25519_hss::shared::reference_boundary::visible_boundary_from_output]:
    Source: 'src/shared/reference_boundary.rs', lines 10:0-16:1
    Visibility: public -/
def shared.reference_boundary.visible_boundary_from_output
  (output : shared.reference.FExpandOutput) :
  Result shared.reference_boundary.FExpandVisibleBoundary
  := do
  ok
    {
      canonical_seed := output.d,
      x_client_base := output.x_client_base,
      x_relayer_base := output.x_relayer_base
    }

/-- [ed25519_hss::shared::reference_boundary::eval_f_expand_visible_boundary]:
    Source: 'src/shared/reference_boundary.rs', lines 18:0-21:1
    Visibility: public -/
def shared.reference_boundary.eval_f_expand_visible_boundary
  (input : shared.reference.FExpandInput) :
  Result (core.result.Result shared.reference_boundary.FExpandVisibleBoundary
    shared.error.ProtoError)
  := do
  let r ← shared.reference.eval_f_expand input
  let cf ←
    core.result.Result.Insts.CoreOpsTry_traitTryTResultInfallibleE.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    let fvb ← shared.reference_boundary.visible_boundary_from_output val
    ok (core.result.Result.Ok fvb)
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
      shared.reference_boundary.FExpandVisibleBoundary (core.convert.FromSame
      shared.error.ProtoError) residual

end ed25519_hss
