/**
 * secp256k1 group order `n`.
 *
 * This is the order of the prime-order subgroup generated by `G` (the base point),
 * as specified by SEC 2 (Recommended Elliptic Curve Domain Parameters).
 *
 * Important:
 * - This is **not** the field modulus `p` (used for x/y coordinate arithmetic).
 * - Scalars for secp256k1 signing/keygen are interpreted modulo `n`.
 *
 * Used by the threshold-secp256k1 ECDSA stack to reduce HKDF-derived bytes into a
 * non-zero scalar in `[1, n-1]`.
 */
export const SECP256K1_ORDER = BigInt(
  '0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364141',
);
