[alias]
hss-fv = "run --manifest-path crates/ed25519-hss/Cargo.toml --bin formal_verification_tasks --"
yao-fv = "run --locked --quiet --manifest-path crates/ed25519-yao/formal-verification/tasks/Cargo.toml --"
