export type {
  AuthenticatorOperation,
  AuthenticatorPort,
  AuthenticatorResult,
  BuildEcdsaRoleLocalExportArtifactAuthorization,
  BuildEcdsaRoleLocalExportArtifactErrorCode,
  BuildEcdsaRoleLocalExportArtifactInput,
  BuildEcdsaRoleLocalExportArtifactOutput,
  BootstrapEcdsaSessionRouteFailureCode,
  BootstrapEcdsaSessionRouteInput,
  BootstrapEcdsaSessionRouteOutput,
  ClientSecretSource,
  ClockPort,
  CleanupMalformedEcdsaRoleLocalRecordInput,
  CleanupMalformedEcdsaRoleLocalRecordResult,
  CredentialIdB64u,
  DurableRecordStore,
  EcdsaBootstrapSecretSource,
  EcdsaBootstrapRouteAuth,
  EcdsaClientBootstrapFacts,
  EcdsaGroupPublicKey33B64u,
  EcdsaPreparePublicFacts,
  EcdsaProvisioningFailureCode,
  EcdsaProvisioningState,
  EcdsaRelayerClient,
  EcdsaRelayerPublicIdentity,
  EcdsaRoleLocalAuthMethod,
  EcdsaRoleLocalMaterialState,
  EcdsaRoleLocalPendingStateBlob,
  EcdsaRoleLocalPublicFacts,
  EcdsaRoleLocalRecordParseResult,
  EcdsaRoleLocalReadyRecord,
  EcdsaRoleLocalReadyStateBlob,
  EmailOtpWorkerIssuedSessionHandle,
  EmailOtpWorkerIssuedSessionHandleInput,
  EmailOtpWorkerSessionSecretSource,
  Fido2HmacSecretSource,
  FinalizeEcdsaClientBootstrapErrorCode,
  FinalizeEcdsaClientBootstrapInput,
  FinalizeEcdsaClientBootstrapOutput,
  HttpTransport,
  LoadEcdsaRoleLocalReadyRecordInput,
  LoadEcdsaRoleLocalReadyRecordResult,
  PlatformKind,
  PlatformResult,
  PlatformRuntime,
  PrepareEcdsaClientBootstrapErrorCode,
  PrepareEcdsaClientBootstrapInput,
  PrepareEcdsaClientBootstrapOutput,
  PersistEcdsaRoleLocalReadyRecordInput,
  PersistEcdsaRoleLocalReadyRecordResult,
  RandomSource,
  RelayerResult,
  RelayerKeyId,
  RequiredPrfAuthenticatorSuccess,
  SecureEnclaveWrappedSecretSource,
  SecureSecretStore,
  SignerCryptoInvocationErrorCode,
  SignerCryptoPort,
  SignerCryptoResult,
  WebAuthnPrfFirstSecretSource,
} from './types';
export {
  assertNeverPlatform,
  buildEmailOtpWorkerIssuedSessionHandle,
  buildEmailOtpWorkerSessionSecretSource,
  buildFido2HmacSecretSource,
  buildRelayerKeyId,
  parseEmailOtpWorkerIssuedSessionHandle,
  buildSecureEnclaveWrappedSecretSource,
  buildWebAuthnPrfFirstSecretSource,
  buildWebAuthnPrfFirstSecretSourceFromParts,
  platformKindLabel,
} from './types';
export {
  createBrowserPlatformRuntime,
  getBrowserPlatformIndexedDB,
  type BrowserDurableRecordStore,
  type BrowserPlatformRuntime,
} from './browser/createBrowserPlatformRuntime';
export {
  parseGeneratedBuildEcdsaRoleLocalExportArtifactOutput,
  parseGeneratedFinalizeEcdsaClientBootstrapOutput,
  parseGeneratedPrepareEcdsaClientBootstrapOutput,
  toGeneratedBuildEcdsaRoleLocalExportArtifactCommand,
  toGeneratedFinalizeEcdsaClientBootstrapCommand,
  toGeneratedPrepareEcdsaClientBootstrapCommand,
  type GeneratedBuildEcdsaRoleLocalExportArtifactCommand,
  type GeneratedBuildEcdsaRoleLocalExportArtifactOutput,
  type GeneratedFinalizeEcdsaClientBootstrapCommand,
  type GeneratedFinalizeEcdsaClientBootstrapOutput,
  type GeneratedPrepareEcdsaClientBootstrapCommand,
  type GeneratedPrepareEcdsaClientBootstrapOutput,
} from './signerCoreCommandAdapters';
export {
  buildEcdsaRoleLocalEmailOtpAuthMethod,
  buildEcdsaRoleLocalPasskeyAuthMethod,
  buildEcdsaRoleLocalPublicFacts,
  buildEcdsaRoleLocalReadyRecord,
  ecdsaRoleLocalReadyRecordMatchesInput,
  ecdsaRoleLocalReadyRecordStorageKey,
  parseEcdsaRoleLocalReadyRecord,
  parseRawEcdsaRoleLocalRecord,
  parseThresholdEcdsaSessionRecordAsRoleLocalExportMaterial,
  parseThresholdEcdsaSessionRecordAsRoleLocalWorkerExportMaterial,
  parseThresholdEcdsaSessionRecordAsRoleLocalReadyRecord,
  serializeEcdsaRoleLocalReadyRecord,
} from '@/core/signingEngine/session/persistence/ecdsaRoleLocalRecords';
