export type {
  AuthenticatorOperation,
  AuthenticatorPort,
  AuthenticatorResult,
  ClientSecretSource,
  ClockPort,
  CleanupMalformedEcdsaRoleLocalRecordInput,
  CleanupMalformedEcdsaRoleLocalRecordResult,
  DurableRecordStore,
  EcdsaBootstrapSecretSource,
  EcdsaRoleLocalPendingStateBlob,
  EcdsaRoleLocalPublicFacts,
  EcdsaRoleLocalRecordParseResult,
  EcdsaRoleLocalReadyRecord,
  EcdsaRoleLocalReadyStateBlob,
  EmailOtpWorkerIssuedSessionHandle,
  EmailOtpWorkerIssuedSessionHandleInput,
  EmailOtpWorkerSessionSecretSource,
  Fido2HmacSecretSource,
  FinalizeEcdsaClientBootstrapErrorCode,
  FinalizeEcdsaClientBootstrapInput,
  FinalizeEcdsaClientBootstrapOutput,
  HttpTransport,
  LoadEcdsaRoleLocalReadyRecordInput,
  LoadEcdsaRoleLocalReadyRecordResult,
  PlatformKind,
  PlatformResult,
  PlatformRuntime,
  PrepareEcdsaClientBootstrapErrorCode,
  PrepareEcdsaClientBootstrapInput,
  PrepareEcdsaClientBootstrapOutput,
  PersistEcdsaRoleLocalReadyRecordInput,
  PersistEcdsaRoleLocalReadyRecordResult,
  RandomSource,
  RequiredPrfAuthenticatorSuccess,
  SecureEnclaveWrappedSecretSource,
  SecureSecretStore,
  SignerCryptoInvocationErrorCode,
  SignerCryptoPort,
  SignerCryptoResult,
  WebAuthnPrfFirstSecretSource,
} from './types';
export {
  assertNeverPlatform,
  buildEmailOtpWorkerIssuedSessionHandle,
  buildEmailOtpWorkerSessionSecretSource,
  buildFido2HmacSecretSource,
  parseEmailOtpWorkerIssuedSessionHandle,
  buildSecureEnclaveWrappedSecretSource,
  buildWebAuthnPrfFirstSecretSource,
  platformKindLabel,
} from './types';
export {
  createBrowserPlatformRuntime,
  getBrowserPlatformIndexedDB,
  type BrowserDurableRecordStore,
  type BrowserPlatformRuntime,
} from './browser/createBrowserPlatformRuntime';
export {
  buildEcdsaRoleLocalReadyRecordFromLegacyState,
  ecdsaRoleLocalReadyRecordMatchesInput,
  ecdsaRoleLocalReadyRecordStorageKey,
  parseEcdsaRoleLocalReadyRecord,
  parseRawEcdsaRoleLocalRecord,
  parseThresholdEcdsaSessionRecordAsRoleLocalExportMaterial,
  parseThresholdEcdsaSessionRecordAsRoleLocalWorkerExportMaterial,
  parseThresholdEcdsaSessionRecordAsRoleLocalReadyRecord,
  serializeEcdsaRoleLocalReadyRecord,
} from './ecdsaRoleLocalRecords';
