-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [ecdsa_hss]: function definitions
import Aeneas
import EcdsaHss.Types
import EcdsaHss.FunsExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace ecdsa_hss

/-- Trait implementation: [alloc::string::{core::convert::From<&0 (str)> for alloc::string::String}]
    Source: '/rustc/library/alloc/src/string.rs', lines 3110:0-3110:26
    Name pattern: [core::convert::From<alloc::string::String, &'0 str>] -/
@[reducible, rust_trait_impl
  "core::convert::From<alloc::string::String, &'0 str>"]
def alloc.string.String.Insts.CoreConvertFromShared0Str : core.convert.From
  String Str := {
  from_ := alloc.string.String.Insts.CoreConvertFromShared0Str.from
}

/-- [ecdsa_hss::client::{ecdsa_hss::client::ClientOutputV1}::allowed_output_kind]:
    Source: 'src/client/mod.rs', lines 32:4-39:5
    Visibility: public -/
def client.ClientOutputV1.allowed_output_kind
  (self : client.ClientOutputV1) : Result wire.AllowedOutputKindV1 := do
  match self with
  | client.ClientOutputV1.NonExport _ =>
    ok wire.AllowedOutputKindV1.ThresholdMaterialOnly
  | client.ClientOutputV1.ExplicitExport _ =>
    ok wire.AllowedOutputKindV1.ThresholdMaterialAndCanonicalSecret

/-- [ecdsa_hss::server::{ecdsa_hss::server::FinalizedServerSessionV1}::validate_finalize_envelope]:
    Source: 'src/server/mod.rs', lines 127:4-154:5
    Visibility: public -/
def server.FinalizedServerSessionV1.validate_finalize_envelope
  (self : server.FinalizedServerSessionV1) (finalize : wire.FinalizeEnvelopeV1)
  :
  Result (core.result.Result Unit signer_core.error.SignerCoreError)
  := do
  let b ←
    wire.ServerEvalOperationV1.Insts.CoreCmpPartialEqServerEvalOperationV1.ne
      finalize.operation self.operation
  if b
  then
    let sce ←
      signer_core.error.SignerCoreError.invalid_input (core.convert.IntoFrom
        alloc.string.String.Insts.CoreConvertFromShared0Str) (toStr
        "finalize envelope operation does not match staged server operation")
    ok (core.result.Result.Err sce)
  else
    if finalize.raw_root_material_dropped
    then
      if self.retained.raw_root_material_dropped
      then
        let b1 ←
          core.array.equality.PartialEqArray.ne core.cmp.PartialEqU8
            finalize.threshold_public_key33
            self.retained.threshold_public_key33
        if b1
        then
          let sce ←
            signer_core.error.SignerCoreError.invalid_input
              (core.convert.IntoFrom
              alloc.string.String.Insts.CoreConvertFromShared0Str) (toStr
              "finalize envelope threshold public key does not match retained server state")
          ok (core.result.Result.Err sce)
        else
          let b2 ←
            core.array.equality.PartialEqArray.ne core.cmp.PartialEqU8
              finalize.threshold_ethereum_address20
              self.retained.threshold_ethereum_address20
          if b2
          then
            let sce ←
              signer_core.error.SignerCoreError.invalid_input
                (core.convert.IntoFrom
                alloc.string.String.Insts.CoreConvertFromShared0Str) (toStr
                "finalize envelope threshold ethereum address does not match retained server state")
            ok (core.result.Result.Err sce)
          else
            if finalize.retry_counter != self.retained.retry_counter
            then
              let sce ←
                signer_core.error.SignerCoreError.invalid_input
                  (core.convert.IntoFrom
                  alloc.string.String.Insts.CoreConvertFromShared0Str) (toStr
                  "finalize envelope retry counter does not match retained server state")
              ok (core.result.Result.Err sce)
            else ok (core.result.Result.Ok ())
      else
        let sce ←
          signer_core.error.SignerCoreError.invalid_input
            (core.convert.IntoFrom
            alloc.string.String.Insts.CoreConvertFromShared0Str) (toStr
            "finalize requires raw root material to be dropped")
        ok (core.result.Result.Err sce)
    else
      let sce ←
        signer_core.error.SignerCoreError.invalid_input (core.convert.IntoFrom
          alloc.string.String.Insts.CoreConvertFromShared0Str) (toStr
          "finalize requires raw root material to be dropped")
      ok (core.result.Result.Err sce)

/-- [ecdsa_hss::wire::{ecdsa_hss::wire::ServerEvalOperationV1}::allowed_output_kind]:
    Source: 'src/wire/mod.rs', lines 34:4-43:5
    Visibility: public -/
def wire.ServerEvalOperationV1.allowed_output_kind
  (self : wire.ServerEvalOperationV1) : Result wire.AllowedOutputKindV1 := do
  match self with
  | wire.ServerEvalOperationV1.RegistrationBootstrap =>
    ok wire.AllowedOutputKindV1.ThresholdMaterialOnly
  | wire.ServerEvalOperationV1.SessionBootstrap =>
    ok wire.AllowedOutputKindV1.ThresholdMaterialOnly
  | wire.ServerEvalOperationV1.NonExportSign =>
    ok wire.AllowedOutputKindV1.ThresholdMaterialOnly
  | wire.ServerEvalOperationV1.ExplicitKeyExport =>
    ok wire.AllowedOutputKindV1.ThresholdMaterialAndCanonicalSecret

/-- [ecdsa_hss::server::reference_boundary::operation_boundary_from_operation_v1]:
    Source: 'src/server/reference_boundary.rs', lines 67:0-74:1
    Visibility: public -/
def server.reference_boundary.operation_boundary_from_operation_v1
  (operation : wire.ServerEvalOperationV1) :
  Result server.reference_boundary.VisibleOperationBoundaryV1
  := do
  let aokv ← wire.ServerEvalOperationV1.allowed_output_kind operation
  ok { operation, allowed_output_kind := aokv }

/-- [ecdsa_hss::server::reference_boundary::explicit_export_boundary_from_output_v1]:
    Source: 'src/server/reference_boundary.rs', lines 142:0-155:1 -/
def server.reference_boundary.explicit_export_boundary_from_output_v1
  (output : client.ExplicitExportClientOutputV1) :
  Result server.reference_boundary.VisibleExplicitExportBoundaryV1
  := do
  ok
    {
      canonical_x32 := output.canonical_x32,
      canonical_public_key33 := output.canonical_public_key33,
      canonical_ethereum_address20 := output.canonical_ethereum_address20,
      x_client32 := output.x_client32,
      client_public_key33 := output.client_public_key33,
      threshold_public_key33 := output.threshold_public_key33,
      threshold_ethereum_address20 := output.threshold_ethereum_address20,
      retry_counter := output.retry_counter
    }

/-- [ecdsa_hss::server::reference_boundary::non_export_boundary_from_output_v1]:
    Source: 'src/server/reference_boundary.rs', lines 130:0-140:1 -/
def server.reference_boundary.non_export_boundary_from_output_v1
  (output : client.NonExportClientOutputV1) :
  Result server.reference_boundary.VisibleNonExportBoundaryV1
  := do
  ok
    {
      x_client32 := output.x_client32,
      client_public_key33 := output.client_public_key33,
      threshold_public_key33 := output.threshold_public_key33,
      threshold_ethereum_address20 := output.threshold_ethereum_address20,
      retry_counter := output.retry_counter
    }

/-- [ecdsa_hss::server::reference_boundary::visible_client_boundary_from_output_v1]:
    Source: 'src/server/reference_boundary.rs', lines 76:0-85:1
    Visibility: public -/
def server.reference_boundary.visible_client_boundary_from_output_v1
  (output : client.ClientOutputV1) :
  Result server.reference_boundary.VisibleClientBoundaryV1
  := do
  match output with
  | client.ClientOutputV1.NonExport output1 =>
    let vnebv ←
      server.reference_boundary.non_export_boundary_from_output_v1 output1
    ok (server.reference_boundary.VisibleClientBoundaryV1.NonExport vnebv)
  | client.ClientOutputV1.ExplicitExport output1 =>
    let veebv ←
      server.reference_boundary.explicit_export_boundary_from_output_v1 output1
    ok (server.reference_boundary.VisibleClientBoundaryV1.ExplicitExport veebv)

/-- [ecdsa_hss::server::reference_boundary::visible_finalize_boundary_from_envelope_v1]:
    Source: 'src/server/reference_boundary.rs', lines 87:0-97:1
    Visibility: public -/
def server.reference_boundary.visible_finalize_boundary_from_envelope_v1
  (finalize : wire.FinalizeEnvelopeV1) :
  Result server.reference_boundary.VisibleFinalizeBoundaryV1
  := do
  ok
    {
      operation := finalize.operation,
      raw_root_material_dropped := finalize.raw_root_material_dropped,
      threshold_public_key33 := finalize.threshold_public_key33,
      threshold_ethereum_address20 := finalize.threshold_ethereum_address20,
      retry_counter := finalize.retry_counter
    }

/-- [ecdsa_hss::server::reference_boundary::retained_state_boundary_from_retained_v1]:
    Source: 'src/server/reference_boundary.rs', lines 157:0-168:1 -/
def server.reference_boundary.retained_state_boundary_from_retained_v1
  (retained : server.RetainedServerStateV1) :
  Result server.reference_boundary.VisibleRetainedServerStateBoundaryV1
  := do
  ok
    {
      raw_root_material_dropped := retained.raw_root_material_dropped,
      relayer_threshold_share32 := retained.relayer_threshold_share32,
      relayer_public_key33 := retained.relayer_public_key33,
      threshold_public_key33 := retained.threshold_public_key33,
      threshold_ethereum_address20 := retained.threshold_ethereum_address20,
      retry_counter := retained.retry_counter
    }

/-- [ecdsa_hss::server::reference_boundary::visible_retained_state_boundary_from_finalized_session_v1]:
    Source: 'src/server/reference_boundary.rs', lines 99:0-103:1
    Visibility: public -/
def
  server.reference_boundary.visible_retained_state_boundary_from_finalized_session_v1
  (session : server.FinalizedServerSessionV1) :
  Result server.reference_boundary.VisibleRetainedServerStateBoundaryV1
  := do
  server.reference_boundary.retained_state_boundary_from_retained_v1
    session.retained

/-- [ecdsa_hss::server::reference_boundary::visible_boundary_from_respond_response_v1]:
    Source: 'src/server/reference_boundary.rs', lines 105:0-128:1
    Visibility: public -/
def server.reference_boundary.visible_boundary_from_respond_response_v1
  (response : server.RespondResponseV1) :
  Result (core.result.Result server.reference_boundary.VisibleRespondBoundaryV1
    signer_core.error.SignerCoreError)
  := do
  let r ←
    server.FinalizedServerSessionV1.validate_finalize_envelope
      response.finalized_server_session response.finalize
  let cf ←
    core.result.Result.Insts.CoreOpsTry_traitTryTResultInfallibleE.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue _ =>
    let operation ←
      server.reference_boundary.operation_boundary_from_operation_v1
        response.finalized_server_session.operation
    let aokv ←
      client.ClientOutputV1.allowed_output_kind response.client_output
    let b ←
      wire.AllowedOutputKindV1.Insts.CoreCmpPartialEqAllowedOutputKindV1.ne
        operation.allowed_output_kind aokv
    if b
    then
      let sce ←
        signer_core.error.SignerCoreError.invalid_input (core.convert.IntoFrom
          alloc.string.String.Insts.CoreConvertFromShared0Str) (toStr
          "client output kind does not match operation output policy")
      ok (core.result.Result.Err sce)
    else
      let vcbv ←
        server.reference_boundary.visible_client_boundary_from_output_v1
          response.client_output
      let vfbv ←
        server.reference_boundary.visible_finalize_boundary_from_envelope_v1
          response.finalize
      let vrssbv ←
        server.reference_boundary.visible_retained_state_boundary_from_finalized_session_v1
          response.finalized_server_session
      ok (core.result.Result.Ok
        {
          operation,
          client_output := vcbv,
          finalize := vfbv,
          retained := vrssbv
        })
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
      server.reference_boundary.VisibleRespondBoundaryV1 (core.convert.FromSame
      signer_core.error.SignerCoreError) residual

end ecdsa_hss
