-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [ecdsa_hss]: function definitions
import Aeneas
import EcdsaHss.Types
import EcdsaHss.FunsExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace ecdsa_hss

/-- Trait implementation: [alloc::string::{core::convert::From<&0 (str)> for alloc::string::String}]
    Source: '/rustc/library/alloc/src/string.rs', lines 3110:0-3110:26
    Name pattern: [core::convert::From<alloc::string::String, &'0 str>] -/
@[reducible, rust_trait_impl
  "core::convert::From<alloc::string::String, &'0 str>"]
def alloc.string.String.Insts.CoreConvertFromShared0Str : core.convert.From
  String Str := {
  from_ := alloc.string.String.Insts.CoreConvertFromShared0Str.from
}

/-- [ecdsa_hss::client::{ecdsa_hss::client::ClientOutputV1}::allowed_output_kind]:
    Source: 'src/client/mod.rs', lines 32:4-39:5
    Visibility: public -/
def client.ClientOutputV1.allowed_output_kind
  (self : client.ClientOutputV1) : Result wire.AllowedOutputKindV1 := do
  match self with
  | client.ClientOutputV1.NonExport _ =>
    ok wire.AllowedOutputKindV1.ThresholdMaterialOnly
  | client.ClientOutputV1.ExplicitExport _ =>
    ok wire.AllowedOutputKindV1.ThresholdMaterialAndCanonicalSecret

/-- [ecdsa_hss::server::{ecdsa_hss::server::FinalizedServerSessionV1}::validate_finalize_envelope]:
    Source: 'src/server/mod.rs', lines 127:4-154:5
    Visibility: public -/
def server.FinalizedServerSessionV1.validate_finalize_envelope
  (self : server.FinalizedServerSessionV1) (finalize : wire.FinalizeEnvelopeV1)
  :
  Result (core.result.Result Unit signer_core.error.SignerCoreError)
  := do
  let b ←
    wire.ServerEvalOperationV1.Insts.CoreCmpPartialEqServerEvalOperationV1.ne
      finalize.operation self.operation
  if b
  then
    let sce ←
      signer_core.error.SignerCoreError.invalid_input (core.convert.IntoFrom
        alloc.string.String.Insts.CoreConvertFromShared0Str) (toStr
        "finalize envelope operation does not match staged server operation")
    ok (core.result.Result.Err sce)
  else
    if finalize.raw_root_material_dropped
    then
      if self.retained.raw_root_material_dropped
      then
        let b1 ←
          core.array.equality.PartialEqArray.ne core.cmp.PartialEqU8
            finalize.threshold_public_key33
            self.retained.threshold_public_key33
        if b1
        then
          let sce ←
            signer_core.error.SignerCoreError.invalid_input
              (core.convert.IntoFrom
              alloc.string.String.Insts.CoreConvertFromShared0Str) (toStr
              "finalize envelope threshold public key does not match retained server state")
          ok (core.result.Result.Err sce)
        else
          let b2 ←
            core.array.equality.PartialEqArray.ne core.cmp.PartialEqU8
              finalize.threshold_ethereum_address20
              self.retained.threshold_ethereum_address20
          if b2
          then
            let sce ←
              signer_core.error.SignerCoreError.invalid_input
                (core.convert.IntoFrom
                alloc.string.String.Insts.CoreConvertFromShared0Str) (toStr
                "finalize envelope threshold ethereum address does not match retained server state")
            ok (core.result.Result.Err sce)
          else
            if finalize.retry_counter != self.retained.retry_counter
            then
              let sce ←
                signer_core.error.SignerCoreError.invalid_input
                  (core.convert.IntoFrom
                  alloc.string.String.Insts.CoreConvertFromShared0Str) (toStr
                  "finalize envelope retry counter does not match retained server state")
              ok (core.result.Result.Err sce)
            else ok (core.result.Result.Ok ())
      else
        let sce ←
          signer_core.error.SignerCoreError.invalid_input
            (core.convert.IntoFrom
            alloc.string.String.Insts.CoreConvertFromShared0Str) (toStr
            "finalize requires raw root material to be dropped")
        ok (core.result.Result.Err sce)
    else
      let sce ←
        signer_core.error.SignerCoreError.invalid_input (core.convert.IntoFrom
          alloc.string.String.Insts.CoreConvertFromShared0Str) (toStr
          "finalize requires raw root material to be dropped")
      ok (core.result.Result.Err sce)

/-- [ecdsa_hss::wire::{ecdsa_hss::wire::ServerEvalOperationV1}::allowed_output_kind]:
    Source: 'src/wire/mod.rs', lines 34:4-43:5
    Visibility: public -/
def wire.ServerEvalOperationV1.allowed_output_kind
  (self : wire.ServerEvalOperationV1) : Result wire.AllowedOutputKindV1 := do
  match self with
  | wire.ServerEvalOperationV1.RegistrationBootstrap =>
    ok wire.AllowedOutputKindV1.ThresholdMaterialOnly
  | wire.ServerEvalOperationV1.SessionBootstrap =>
    ok wire.AllowedOutputKindV1.ThresholdMaterialOnly
  | wire.ServerEvalOperationV1.NonExportSign =>
    ok wire.AllowedOutputKindV1.ThresholdMaterialOnly
  | wire.ServerEvalOperationV1.ExplicitKeyExport =>
    ok wire.AllowedOutputKindV1.ThresholdMaterialAndCanonicalSecret

/-- [ecdsa_hss::server::reference_boundary::operation_boundary_from_operation_v1]:
    Source: 'src/server/reference_boundary.rs', lines 104:0-111:1
    Visibility: public -/
def server.reference_boundary.operation_boundary_from_operation_v1
  (operation : wire.ServerEvalOperationV1) :
  Result server.reference_boundary.VisibleOperationBoundaryV1
  := do
  let aokv ← wire.ServerEvalOperationV1.allowed_output_kind operation
  ok { operation, allowed_output_kind := aokv }

/-- [ecdsa_hss::server::reference_boundary::explicit_export_boundary_from_output_v1]:
    Source: 'src/server/reference_boundary.rs', lines 242:0-255:1 -/
def server.reference_boundary.explicit_export_boundary_from_output_v1
  (output : client.ExplicitExportClientOutputV1) :
  Result server.reference_boundary.VisibleExplicitExportBoundaryV1
  := do
  ok
    {
      canonical_x32 := output.canonical_x32,
      canonical_public_key33 := output.canonical_public_key33,
      canonical_ethereum_address20 := output.canonical_ethereum_address20,
      x_client32 := output.x_client32,
      client_public_key33 := output.client_public_key33,
      threshold_public_key33 := output.threshold_public_key33,
      threshold_ethereum_address20 := output.threshold_ethereum_address20,
      retry_counter := output.retry_counter
    }

/-- [ecdsa_hss::server::reference_boundary::non_export_boundary_from_output_v1]:
    Source: 'src/server/reference_boundary.rs', lines 230:0-240:1 -/
def server.reference_boundary.non_export_boundary_from_output_v1
  (output : client.NonExportClientOutputV1) :
  Result server.reference_boundary.VisibleNonExportBoundaryV1
  := do
  ok
    {
      x_client32 := output.x_client32,
      client_public_key33 := output.client_public_key33,
      threshold_public_key33 := output.threshold_public_key33,
      threshold_ethereum_address20 := output.threshold_ethereum_address20,
      retry_counter := output.retry_counter
    }

/-- [ecdsa_hss::server::reference_boundary::visible_client_boundary_from_output_v1]:
    Source: 'src/server/reference_boundary.rs', lines 113:0-122:1
    Visibility: public -/
def server.reference_boundary.visible_client_boundary_from_output_v1
  (output : client.ClientOutputV1) :
  Result server.reference_boundary.VisibleClientBoundaryV1
  := do
  match output with
  | client.ClientOutputV1.NonExport output1 =>
    let vnebv ←
      server.reference_boundary.non_export_boundary_from_output_v1 output1
    ok (server.reference_boundary.VisibleClientBoundaryV1.NonExport vnebv)
  | client.ClientOutputV1.ExplicitExport output1 =>
    let veebv ←
      server.reference_boundary.explicit_export_boundary_from_output_v1 output1
    ok (server.reference_boundary.VisibleClientBoundaryV1.ExplicitExport veebv)

/-- [ecdsa_hss::server::reference_boundary::visible_finalize_boundary_from_envelope_v1]:
    Source: 'src/server/reference_boundary.rs', lines 124:0-134:1
    Visibility: public -/
def server.reference_boundary.visible_finalize_boundary_from_envelope_v1
  (finalize : wire.FinalizeEnvelopeV1) :
  Result server.reference_boundary.VisibleFinalizeBoundaryV1
  := do
  ok
    {
      operation := finalize.operation,
      raw_root_material_dropped := finalize.raw_root_material_dropped,
      threshold_public_key33 := finalize.threshold_public_key33,
      threshold_ethereum_address20 := finalize.threshold_ethereum_address20,
      retry_counter := finalize.retry_counter
    }

/-- [ecdsa_hss::server::reference_boundary::retained_state_boundary_from_retained_v1]:
    Source: 'src/server/reference_boundary.rs', lines 257:0-268:1 -/
def server.reference_boundary.retained_state_boundary_from_retained_v1
  (retained : server.RetainedServerStateV1) :
  Result server.reference_boundary.VisibleRetainedServerStateBoundaryV1
  := do
  ok
    {
      raw_root_material_dropped := retained.raw_root_material_dropped,
      relayer_threshold_share32 := retained.relayer_threshold_share32,
      relayer_public_key33 := retained.relayer_public_key33,
      threshold_public_key33 := retained.threshold_public_key33,
      threshold_ethereum_address20 := retained.threshold_ethereum_address20,
      retry_counter := retained.retry_counter
    }

/-- [ecdsa_hss::server::reference_boundary::visible_retained_state_boundary_from_finalized_session_v1]:
    Source: 'src/server/reference_boundary.rs', lines 136:0-140:1
    Visibility: public -/
def
  server.reference_boundary.visible_retained_state_boundary_from_finalized_session_v1
  (session : server.FinalizedServerSessionV1) :
  Result server.reference_boundary.VisibleRetainedServerStateBoundaryV1
  := do
  server.reference_boundary.retained_state_boundary_from_retained_v1
    session.retained

/-- [ecdsa_hss::server::reference_boundary::visible_boundary_from_respond_response_v1]:
    Source: 'src/server/reference_boundary.rs', lines 142:0-165:1
    Visibility: public -/
def server.reference_boundary.visible_boundary_from_respond_response_v1
  (response : server.RespondResponseV1) :
  Result (core.result.Result server.reference_boundary.VisibleRespondBoundaryV1
    signer_core.error.SignerCoreError)
  := do
  let r ←
    server.FinalizedServerSessionV1.validate_finalize_envelope
      response.finalized_server_session response.finalize
  let cf ←
    core.result.Result.Insts.CoreOpsTry_traitTryTResultInfallibleE.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue _ =>
    let operation ←
      server.reference_boundary.operation_boundary_from_operation_v1
        response.finalized_server_session.operation
    let aokv ←
      client.ClientOutputV1.allowed_output_kind response.client_output
    let b ←
      wire.AllowedOutputKindV1.Insts.CoreCmpPartialEqAllowedOutputKindV1.ne
        operation.allowed_output_kind aokv
    if b
    then
      let sce ←
        signer_core.error.SignerCoreError.invalid_input (core.convert.IntoFrom
          alloc.string.String.Insts.CoreConvertFromShared0Str) (toStr
          "client output kind does not match operation output policy")
      ok (core.result.Result.Err sce)
    else
      let vcbv ←
        server.reference_boundary.visible_client_boundary_from_output_v1
          response.client_output
      let vfbv ←
        server.reference_boundary.visible_finalize_boundary_from_envelope_v1
          response.finalize
      let vrssbv ←
        server.reference_boundary.visible_retained_state_boundary_from_finalized_session_v1
          response.finalized_server_session
      ok (core.result.Result.Ok
        {
          operation,
          client_output := vcbv,
          finalize := vfbv,
          retained := vrssbv
        })
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
      server.reference_boundary.VisibleRespondBoundaryV1 (core.convert.FromSame
      signer_core.error.SignerCoreError) residual

/-- [ecdsa_hss::shared::context::{core::clone::Clone for ecdsa_hss::shared::context::EcdsaHssStableKeyContextV1}::clone]:
    Source: 'src/shared/context.rs', lines 9:16-9:21
    Visibility: public -/
def shared.context.EcdsaHssStableKeyContextV1.Insts.CoreCloneClone.clone
  (self : shared.context.EcdsaHssStableKeyContextV1) :
  Result shared.context.EcdsaHssStableKeyContextV1
  := do
  let s ←
    alloc.string.String.Insts.CoreCloneClone.clone self.wallet_session_user_id
  let s1 ← alloc.string.String.Insts.CoreCloneClone.clone self.subject_id
  let s2 ← alloc.string.String.Insts.CoreCloneClone.clone self.chain_target
  let s3 ←
    alloc.string.String.Insts.CoreCloneClone.clone self.ecdsa_threshold_key_id
  let s4 ←
    alloc.string.String.Insts.CoreCloneClone.clone self.signing_root_id
  let s5 ←
    alloc.string.String.Insts.CoreCloneClone.clone self.signing_root_version
  let s6 ← alloc.string.String.Insts.CoreCloneClone.clone self.key_purpose
  let s7 ← alloc.string.String.Insts.CoreCloneClone.clone self.key_version
  ok
    {
      wallet_session_user_id := s,
      subject_id := s1,
      chain_target := s2,
      ecdsa_threshold_key_id := s3,
      signing_root_id := s4,
      signing_root_version := s5,
      key_purpose := s6,
      key_version := s7
    }

/-- [ecdsa_hss::server::reference_boundary::hidden_eval_input_boundary_from_staged_request_v1]:
    Source: 'src/server/reference_boundary.rs', lines 167:0-178:1
    Visibility: public -/
def server.reference_boundary.hidden_eval_input_boundary_from_staged_request_v1
  (staged : server.StagedServerSessionV1) (request : wire.RespondRequestV1) :
  Result server.reference_boundary.HiddenEvalInputBoundaryV1
  := do
  let aokv ←
    wire.ServerEvalOperationV1.allowed_output_kind staged.prepare.operation
  let ehskcv ←
    shared.context.EcdsaHssStableKeyContextV1.Insts.CoreCloneClone.clone
      staged.prepare.context
  ok
    {
      operation := staged.prepare.operation,
      allowed_output_kind := aokv,
      context := ehskcv,
      y_client32_le := request.y_client32_le,
      y_relayer32_le := staged.y_relayer32_le
    }

/-- [ecdsa_hss::server::reference_boundary::hidden_eval_transport_boundary_from_respond_response_v1]:
    Source: 'src/server/reference_boundary.rs', lines 180:0-189:1
    Visibility: public -/
def
  server.reference_boundary.hidden_eval_transport_boundary_from_respond_response_v1
  (response : server.RespondResponseV1) :
  Result (core.result.Result
    server.reference_boundary.HiddenEvalTransportBoundaryV1
    signer_core.error.SignerCoreError)
  := do
  let r ←
    server.reference_boundary.visible_boundary_from_respond_response_v1
      response
  let cf ←
    core.result.Result.Insts.CoreOpsTry_traitTryTResultInfallibleE.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    ok (core.result.Result.Ok
      {
        operation := val.operation,
        client_output := val.client_output,
        finalize := val.finalize
      })
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
      server.reference_boundary.HiddenEvalTransportBoundaryV1
      (core.convert.FromSame signer_core.error.SignerCoreError) residual

/-- [ecdsa_hss::server::reference_boundary::hidden_eval_persisted_state_boundary_from_finalized_session_v1]:
    Source: 'src/server/reference_boundary.rs', lines 191:0-203:1
    Visibility: public -/
def
  server.reference_boundary.hidden_eval_persisted_state_boundary_from_finalized_session_v1
  (session : server.FinalizedServerSessionV1) :
  Result server.reference_boundary.HiddenEvalPersistedStateBoundaryV1
  := do
  ok
    {
      operation := session.operation,
      raw_root_material_dropped := session.retained.raw_root_material_dropped,
      relayer_threshold_share32 := session.retained.relayer_threshold_share32,
      relayer_public_key33 := session.retained.relayer_public_key33,
      threshold_public_key33 := session.retained.threshold_public_key33,
      threshold_ethereum_address20 :=
        session.retained.threshold_ethereum_address20,
      retry_counter := session.retained.retry_counter
    }

/-- [ecdsa_hss::server::reference_boundary::hidden_eval_boundary_from_staged_request_and_response_v1]:
    Source: 'src/server/reference_boundary.rs', lines 205:0-228:1
    Visibility: public -/
def
  server.reference_boundary.hidden_eval_boundary_from_staged_request_and_response_v1
  (staged : server.StagedServerSessionV1) (request : wire.RespondRequestV1)
  (response : server.RespondResponseV1) :
  Result (core.result.Result server.reference_boundary.HiddenEvalBoundaryV1
    signer_core.error.SignerCoreError)
  := do
  let b ←
    wire.ServerEvalOperationV1.Insts.CoreCmpPartialEqServerEvalOperationV1.ne
      response.finalized_server_session.operation staged.prepare.operation
  if b
  then
    let sce ←
      signer_core.error.SignerCoreError.invalid_input (core.convert.IntoFrom
        alloc.string.String.Insts.CoreConvertFromShared0Str) (toStr
        "respond response operation does not match staged server operation")
    ok (core.result.Result.Err sce)
  else
    let b1 ←
      shared.context.EcdsaHssStableKeyContextV1.Insts.CoreCmpPartialEqEcdsaHssStableKeyContextV1.ne
        response.finalized_server_session.context staged.prepare.context
    if b1
    then
      let sce ←
        signer_core.error.SignerCoreError.invalid_input (core.convert.IntoFrom
          alloc.string.String.Insts.CoreConvertFromShared0Str) (toStr
          "respond response context does not match staged server context")
      ok (core.result.Result.Err sce)
    else
      let heibv ←
        server.reference_boundary.hidden_eval_input_boundary_from_staged_request_v1
          staged request
      let r ←
        server.reference_boundary.hidden_eval_transport_boundary_from_respond_response_v1
          response
      let cf ←
        core.result.Result.Insts.CoreOpsTry_traitTryTResultInfallibleE.branch r
      match cf with
      | core.ops.control_flow.ControlFlow.Continue val =>
        let hepsbv ←
          server.reference_boundary.hidden_eval_persisted_state_boundary_from_finalized_session_v1
            response.finalized_server_session
        ok (core.result.Result.Ok
          { input := heibv, transport := val, persisted := hepsbv })
      | core.ops.control_flow.ControlFlow.Break residual =>
        core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
          server.reference_boundary.HiddenEvalBoundaryV1 (core.convert.FromSame
          signer_core.error.SignerCoreError) residual

end ecdsa_hss
