-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [ecdsa_hss]: external functions.
-- This is a template file: rename it to "FunsExternal.lean" and fill the holes.
import Aeneas
import EcdsaHss.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000
open ecdsa_hss

/-- [core::result::{core::ops::try_trait::Try<T, core::result::Result<core::convert::Infallible, E>> for core::result::Result<T, E>}::branch]:
    Source: '/rustc/library/core/src/result.rs', lines 2172:4-2172:64
    Name pattern: [core::result::{core::ops::try_trait::Try<core::result::Result<@T, @E>, @T, core::result::Result<core::convert::Infallible, @E>>}::branch]
    Visibility: public -/
@[rust_fun
  "core::result::{core::ops::try_trait::Try<core::result::Result<@T, @E>, @T, core::result::Result<core::convert::Infallible, @E>>}::branch"]
axiom core.result.Result.Insts.CoreOpsTry_traitTryTResultInfallibleE.branch
  {T : Type} {E : Type} :
  core.result.Result T E → Result (core.ops.control_flow.ControlFlow
    (core.result.Result core.convert.Infallible E) T)

/-- [core::result::{core::ops::try_trait::FromResidual<core::result::Result<core::convert::Infallible, E>> for core::result::Result<T, F>}::from_residual]:
    Source: '/rustc/library/core/src/result.rs', lines 2187:4-2187:70
    Name pattern: [core::result::{core::ops::try_trait::FromResidual<core::result::Result<@T, @F>, core::result::Result<core::convert::Infallible, @E>>}::from_residual]
    Visibility: public -/
@[rust_fun
  "core::result::{core::ops::try_trait::FromResidual<core::result::Result<@T, @F>, core::result::Result<core::convert::Infallible, @E>>}::from_residual"]
axiom
  core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
  (T : Type) {E : Type} {F : Type} (convertFromInst : core.convert.From F E) :
  core.result.Result core.convert.Infallible E → Result (core.result.Result T
    F)

/-- [alloc::string::{core::clone::Clone for alloc::string::String}::clone]:
    Source: '/rustc/library/alloc/src/string.rs', lines 2351:4-2351:27
    Name pattern: [alloc::string::{core::clone::Clone<alloc::string::String>}::clone]
    Visibility: public -/
@[rust_fun "alloc::string::{core::clone::Clone<alloc::string::String>}::clone"]
axiom alloc.string.String.Insts.CoreCloneClone.clone : String → Result String

/-- [alloc::string::{core::convert::From<&0 (str)> for alloc::string::String}::from]:
    Source: '/rustc/library/alloc/src/string.rs', lines 3115:4-3115:30
    Name pattern: [alloc::string::{core::convert::From<alloc::string::String, &'0 str>}::from]
    Visibility: public -/
@[rust_fun
  "alloc::string::{core::convert::From<alloc::string::String, &'0 str>}::from"]
axiom alloc.string.String.Insts.CoreConvertFromShared0Str.from
  : Str → Result String

/-- [signer_core::error::{signer_core::error::SignerCoreError}::invalid_input]:
    Source: '/Users/pta/Dev/rust/simple-threshold-signer/crates/signer-core/src/error.rs', lines 30:4-30:60
    Name pattern: [signer_core::error::{signer_core::error::SignerCoreError}::invalid_input]
    Visibility: public -/
@[rust_fun
  "signer_core::error::{signer_core::error::SignerCoreError}::invalid_input"]
axiom signer_core.error.SignerCoreError.invalid_input
  {T0 : Type} (coreconvertIntoT0StringInst : core.convert.Into T0 String) :
  T0 → Result signer_core.error.SignerCoreError

/-- [ecdsa_hss::wire::{core::cmp::PartialEq<ecdsa_hss::wire::ServerEvalOperationV1> for ecdsa_hss::wire::ServerEvalOperationV1}::ne]:
    Source: 'src/wire/mod.rs', lines 4:29-4:38
    Visibility: public -/
axiom wire.ServerEvalOperationV1.Insts.CoreCmpPartialEqServerEvalOperationV1.ne
  : wire.ServerEvalOperationV1 → wire.ServerEvalOperationV1 → Result Bool

/-- [ecdsa_hss::wire::{core::cmp::PartialEq<ecdsa_hss::wire::AllowedOutputKindV1> for ecdsa_hss::wire::AllowedOutputKindV1}::ne]:
    Source: 'src/wire/mod.rs', lines 12:29-12:38
    Visibility: public -/
axiom wire.AllowedOutputKindV1.Insts.CoreCmpPartialEqAllowedOutputKindV1.ne
  : wire.AllowedOutputKindV1 → wire.AllowedOutputKindV1 → Result Bool

/-- [ecdsa_hss::shared::context::{core::cmp::PartialEq<ecdsa_hss::shared::context::EcdsaHssContextV1> for ecdsa_hss::shared::context::EcdsaHssContextV1}::ne]:
    Source: 'src/shared/context.rs', lines 8:23-8:32
    Visibility: public -/
axiom
  shared.context.EcdsaHssContextV1.Insts.CoreCmpPartialEqEcdsaHssContextV1.ne
  :
  shared.context.EcdsaHssContextV1 → shared.context.EcdsaHssContextV1 →
    Result Bool

