-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [ecdsa_hss]: type definitions
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

namespace ecdsa_hss

/-- [ecdsa_hss::shared::context::EcdsaHssStableKeyContextV2]
    Source: 'src/lib.rs', lines 4:8-12:9
    Visibility: public -/
structure shared.context.EcdsaHssStableKeyContextV2 where
  wallet_id : String
  rp_id : String
  ecdsa_threshold_key_id : String
  signing_root_id : String
  signing_root_version : String
  key_purpose : String
  key_version : String

/-- [ecdsa_hss::wire::ServerEvalOperationV2]
    Source: 'src/lib.rs', lines 20:4-25:5
    Visibility: public -/
@[discriminant isize]
inductive wire.ServerEvalOperationV2 where
| RegistrationBootstrap : wire.ServerEvalOperationV2
| SessionBootstrap : wire.ServerEvalOperationV2
| NonExportSign : wire.ServerEvalOperationV2
| ExplicitKeyExport : wire.ServerEvalOperationV2

/-- [ecdsa_hss::wire::AllowedOutputKindV2]
    Source: 'src/lib.rs', lines 28:4-31:5
    Visibility: public -/
@[discriminant isize]
inductive wire.AllowedOutputKindV2 where
| ThresholdMaterialOnly : wire.AllowedOutputKindV2
| ThresholdMaterialAndRelayerExportShare : wire.AllowedOutputKindV2

/-- [ecdsa_hss::wire::PrepareEnvelopeV2]
    Source: 'src/lib.rs', lines 49:4-53:5
    Visibility: public -/
structure wire.PrepareEnvelopeV2 where
  operation : wire.ServerEvalOperationV2
  context : shared.context.EcdsaHssStableKeyContextV2
  relayer_key_id : String

/-- [ecdsa_hss::wire::ThresholdRespondRequestV2]
    Source: 'src/lib.rs', lines 56:4-60:5
    Visibility: public -/
structure wire.ThresholdRespondRequestV2 where
  client_public_key33 : Array Std.U8 33#usize
  client_share_retry_counter : Std.U32
  expected_relayer_key_id : String

/-- [ecdsa_hss::wire::FinalizeEnvelopeV2]
    Source: 'src/lib.rs', lines 63:4-74:5
    Visibility: public -/
structure wire.FinalizeEnvelopeV2 where
  operation : wire.ServerEvalOperationV2
  raw_root_material_dropped : Bool
  relayer_key_id : String
  context_binding32 : Array Std.U8 32#usize
  client_public_key33 : Array Std.U8 33#usize
  relayer_public_key33 : Array Std.U8 33#usize
  threshold_public_key33 : Array Std.U8 33#usize
  threshold_ethereum_address20 : Array Std.U8 20#usize
  client_share_retry_counter : Std.U32
  relayer_share_retry_counter : Std.U32

/-- [ecdsa_hss::client::NonExportClientOutputV2]
    Source: 'src/lib.rs', lines 81:4-88:5
    Visibility: public -/
structure client.NonExportClientOutputV2 where
  client_public_key33 : Array Std.U8 33#usize
  relayer_public_key33 : Array Std.U8 33#usize
  threshold_public_key33 : Array Std.U8 33#usize
  threshold_ethereum_address20 : Array Std.U8 20#usize
  client_share_retry_counter : Std.U32
  relayer_share_retry_counter : Std.U32

/-- [ecdsa_hss::client::ExplicitExportClientOutputV2]
    Source: 'src/lib.rs', lines 91:4-99:5
    Visibility: public -/
structure client.ExplicitExportClientOutputV2 where
  relayer_export_share32 : Array Std.U8 32#usize
  client_public_key33 : Array Std.U8 33#usize
  relayer_public_key33 : Array Std.U8 33#usize
  threshold_public_key33 : Array Std.U8 33#usize
  threshold_ethereum_address20 : Array Std.U8 20#usize
  client_share_retry_counter : Std.U32
  relayer_share_retry_counter : Std.U32

/-- [ecdsa_hss::client::ClientOutputV2]
    Source: 'src/lib.rs', lines 102:4-105:5
    Visibility: public -/
@[discriminant isize]
inductive client.ClientOutputV2 where
| NonExport : client.NonExportClientOutputV2 → client.ClientOutputV2
| ExplicitExport :
  client.ExplicitExportClientOutputV2 →
  client.ClientOutputV2

/-- [ecdsa_hss::server::RetainedServerStateV2]
    Source: 'src/lib.rs', lines 128:4-138:5
    Visibility: public -/
structure server.RetainedServerStateV2 where
  raw_root_material_dropped : Bool
  relayer_key_id : String
  relayer_share32 : Array Std.U8 32#usize
  client_public_key33 : Array Std.U8 33#usize
  relayer_public_key33 : Array Std.U8 33#usize
  threshold_public_key33 : Array Std.U8 33#usize
  threshold_ethereum_address20 : Array Std.U8 20#usize
  client_share_retry_counter : Std.U32
  relayer_share_retry_counter : Std.U32

/-- [ecdsa_hss::server::FinalizedServerSessionV2]
    Source: 'src/lib.rs', lines 141:4-145:5
    Visibility: public -/
structure server.FinalizedServerSessionV2 where
  operation : wire.ServerEvalOperationV2
  context : shared.context.EcdsaHssStableKeyContextV2
  retained : server.RetainedServerStateV2

/-- [ecdsa_hss::server::StagedServerSessionV2]
    Source: 'src/lib.rs', lines 148:4-151:5
    Visibility: public -/
structure server.StagedServerSessionV2 where
  prepare : wire.PrepareEnvelopeV2
  y_relayer32_le : Array Std.U8 32#usize

/-- [ecdsa_hss::server::RespondResponseV2]
    Source: 'src/lib.rs', lines 154:4-157:5
    Visibility: public -/
structure server.RespondResponseV2 where
  client_output : client.ClientOutputV2
  finalize : wire.FinalizeEnvelopeV2

/-- [ecdsa_hss::server::boundary::VisibleOperationBoundaryV2]
    Source: 'src/lib.rs', lines 169:8-172:9
    Visibility: public -/
structure server.boundary.VisibleOperationBoundaryV2 where
  operation : wire.ServerEvalOperationV2
  allowed_output_kind : wire.AllowedOutputKindV2

/-- [ecdsa_hss::server::boundary::VisibleNonExportBoundaryV2]
    Source: 'src/lib.rs', lines 175:8-182:9
    Visibility: public -/
structure server.boundary.VisibleNonExportBoundaryV2 where
  client_public_key33 : Array Std.U8 33#usize
  relayer_public_key33 : Array Std.U8 33#usize
  threshold_public_key33 : Array Std.U8 33#usize
  threshold_ethereum_address20 : Array Std.U8 20#usize
  client_share_retry_counter : Std.U32
  relayer_share_retry_counter : Std.U32

/-- [ecdsa_hss::server::boundary::VisibleExplicitExportBoundaryV2]
    Source: 'src/lib.rs', lines 185:8-193:9
    Visibility: public -/
structure server.boundary.VisibleExplicitExportBoundaryV2 where
  relayer_export_share32 : Array Std.U8 32#usize
  client_public_key33 : Array Std.U8 33#usize
  relayer_public_key33 : Array Std.U8 33#usize
  threshold_public_key33 : Array Std.U8 33#usize
  threshold_ethereum_address20 : Array Std.U8 20#usize
  client_share_retry_counter : Std.U32
  relayer_share_retry_counter : Std.U32

/-- [ecdsa_hss::server::boundary::VisibleClientBoundaryV2]
    Source: 'src/lib.rs', lines 196:8-199:9
    Visibility: public -/
@[discriminant isize]
inductive server.boundary.VisibleClientBoundaryV2 where
| NonExport :
  server.boundary.VisibleNonExportBoundaryV2 →
  server.boundary.VisibleClientBoundaryV2
| ExplicitExport :
  server.boundary.VisibleExplicitExportBoundaryV2 →
  server.boundary.VisibleClientBoundaryV2

/-- [ecdsa_hss::server::boundary::VisibleFinalizeBoundaryV2]
    Source: 'src/lib.rs', lines 202:8-213:9
    Visibility: public -/
structure server.boundary.VisibleFinalizeBoundaryV2 where
  operation : wire.ServerEvalOperationV2
  raw_root_material_dropped : Bool
  relayer_key_id : String
  context_binding32 : Array Std.U8 32#usize
  client_public_key33 : Array Std.U8 33#usize
  relayer_public_key33 : Array Std.U8 33#usize
  threshold_public_key33 : Array Std.U8 33#usize
  threshold_ethereum_address20 : Array Std.U8 20#usize
  client_share_retry_counter : Std.U32
  relayer_share_retry_counter : Std.U32

/-- [ecdsa_hss::server::boundary::VisibleRespondBoundaryV2]
    Source: 'src/lib.rs', lines 229:8-233:9
    Visibility: public -/
structure server.boundary.VisibleRespondBoundaryV2 where
  operation : server.boundary.VisibleOperationBoundaryV2
  client_output : server.boundary.VisibleClientBoundaryV2
  finalize : server.boundary.VisibleFinalizeBoundaryV2

/-- [ecdsa_hss::server::boundary::HiddenEvalInputBoundaryV2]
    Source: 'src/lib.rs', lines 236:8-245:9
    Visibility: public -/
structure server.boundary.HiddenEvalInputBoundaryV2 where
  operation : wire.ServerEvalOperationV2
  allowed_output_kind : wire.AllowedOutputKindV2
  context : shared.context.EcdsaHssStableKeyContextV2
  relayer_key_id : String
  client_public_key33 : Array Std.U8 33#usize
  client_share_retry_counter : Std.U32
  expected_relayer_key_id : String
  y_relayer32_le : Array Std.U8 32#usize

/-- [ecdsa_hss::server::boundary::HiddenEvalTransportBoundaryV2]
    Source: 'src/lib.rs', lines 248:8-252:9
    Visibility: public -/
structure server.boundary.HiddenEvalTransportBoundaryV2 where
  operation : server.boundary.VisibleOperationBoundaryV2
  client_output : server.boundary.VisibleClientBoundaryV2
  finalize : server.boundary.VisibleFinalizeBoundaryV2

/-- [ecdsa_hss::server::boundary::HiddenEvalPersistedStateBoundaryV2]
    Source: 'src/lib.rs', lines 255:8-266:9
    Visibility: public -/
structure server.boundary.HiddenEvalPersistedStateBoundaryV2 where
  operation : wire.ServerEvalOperationV2
  raw_root_material_dropped : Bool
  relayer_key_id : String
  relayer_share32 : Array Std.U8 32#usize
  client_public_key33 : Array Std.U8 33#usize
  relayer_public_key33 : Array Std.U8 33#usize
  threshold_public_key33 : Array Std.U8 33#usize
  threshold_ethereum_address20 : Array Std.U8 20#usize
  client_share_retry_counter : Std.U32
  relayer_share_retry_counter : Std.U32

/-- [ecdsa_hss::server::boundary::HiddenEvalBoundaryV2]
    Source: 'src/lib.rs', lines 269:8-273:9
    Visibility: public -/
structure server.boundary.HiddenEvalBoundaryV2 where
  input : server.boundary.HiddenEvalInputBoundaryV2
  transport : server.boundary.HiddenEvalTransportBoundaryV2
  persisted : server.boundary.HiddenEvalPersistedStateBoundaryV2

end ecdsa_hss
