-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [ecdsa_hss]: type definitions
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

namespace ecdsa_hss

/-- [ecdsa_hss::shared::context::EcdsaHssStableKeyContext]
    Source: 'src/lib.rs', lines 4:8-12:9
    Visibility: public -/
structure shared.context.EcdsaHssStableKeyContext where
  wallet_id : String
  rp_id : String
  ecdsa_threshold_key_id : String
  signing_root_id : String
  signing_root_version : String
  key_purpose : String
  key_version : String

/-- [ecdsa_hss::wire::ServerEvalOperation]
    Source: 'src/lib.rs', lines 20:4-25:5
    Visibility: public -/
@[discriminant isize]
inductive wire.ServerEvalOperation where
| RegistrationBootstrap : wire.ServerEvalOperation
| SessionBootstrap : wire.ServerEvalOperation
| NonExportSign : wire.ServerEvalOperation
| ExplicitKeyExport : wire.ServerEvalOperation

/-- [ecdsa_hss::wire::AllowedOutputKind]
    Source: 'src/lib.rs', lines 28:4-31:5
    Visibility: public -/
@[discriminant isize]
inductive wire.AllowedOutputKind where
| ThresholdMaterialOnly : wire.AllowedOutputKind
| ThresholdMaterialAndRelayerExportShare : wire.AllowedOutputKind

/-- [ecdsa_hss::wire::PrepareEnvelope]
    Source: 'src/lib.rs', lines 47:4-51:5
    Visibility: public -/
structure wire.PrepareEnvelope where
  operation : wire.ServerEvalOperation
  context : shared.context.EcdsaHssStableKeyContext
  relayer_key_id : String

/-- [ecdsa_hss::wire::ThresholdRespondRequest]
    Source: 'src/lib.rs', lines 54:4-58:5
    Visibility: public -/
structure wire.ThresholdRespondRequest where
  client_public_key33 : Array Std.U8 33#usize
  client_share_retry_counter : Std.U32
  expected_relayer_key_id : String

/-- [ecdsa_hss::wire::FinalizeEnvelope]
    Source: 'src/lib.rs', lines 61:4-72:5
    Visibility: public -/
structure wire.FinalizeEnvelope where
  operation : wire.ServerEvalOperation
  raw_root_material_dropped : Bool
  relayer_key_id : String
  context_binding32 : Array Std.U8 32#usize
  client_public_key33 : Array Std.U8 33#usize
  relayer_public_key33 : Array Std.U8 33#usize
  threshold_public_key33 : Array Std.U8 33#usize
  threshold_ethereum_address20 : Array Std.U8 20#usize
  client_share_retry_counter : Std.U32
  relayer_share_retry_counter : Std.U32

/-- [ecdsa_hss::client::NonExportClientOutput]
    Source: 'src/lib.rs', lines 79:4-86:5
    Visibility: public -/
structure client.NonExportClientOutput where
  client_public_key33 : Array Std.U8 33#usize
  relayer_public_key33 : Array Std.U8 33#usize
  threshold_public_key33 : Array Std.U8 33#usize
  threshold_ethereum_address20 : Array Std.U8 20#usize
  client_share_retry_counter : Std.U32
  relayer_share_retry_counter : Std.U32

/-- [ecdsa_hss::client::ExplicitExportClientOutput]
    Source: 'src/lib.rs', lines 89:4-97:5
    Visibility: public -/
structure client.ExplicitExportClientOutput where
  relayer_export_share32 : Array Std.U8 32#usize
  client_public_key33 : Array Std.U8 33#usize
  relayer_public_key33 : Array Std.U8 33#usize
  threshold_public_key33 : Array Std.U8 33#usize
  threshold_ethereum_address20 : Array Std.U8 20#usize
  client_share_retry_counter : Std.U32
  relayer_share_retry_counter : Std.U32

/-- [ecdsa_hss::client::ClientOutput]
    Source: 'src/lib.rs', lines 100:4-103:5
    Visibility: public -/
@[discriminant isize]
inductive client.ClientOutput where
| NonExport : client.NonExportClientOutput → client.ClientOutput
| ExplicitExport : client.ExplicitExportClientOutput → client.ClientOutput

/-- [ecdsa_hss::server::RetainedServerState]
    Source: 'src/lib.rs', lines 126:4-136:5
    Visibility: public -/
structure server.RetainedServerState where
  raw_root_material_dropped : Bool
  relayer_key_id : String
  relayer_share32 : Array Std.U8 32#usize
  client_public_key33 : Array Std.U8 33#usize
  relayer_public_key33 : Array Std.U8 33#usize
  threshold_public_key33 : Array Std.U8 33#usize
  threshold_ethereum_address20 : Array Std.U8 20#usize
  client_share_retry_counter : Std.U32
  relayer_share_retry_counter : Std.U32

/-- [ecdsa_hss::server::FinalizedServerSession]
    Source: 'src/lib.rs', lines 139:4-143:5
    Visibility: public -/
structure server.FinalizedServerSession where
  operation : wire.ServerEvalOperation
  context : shared.context.EcdsaHssStableKeyContext
  retained : server.RetainedServerState

/-- [ecdsa_hss::server::StagedServerSession]
    Source: 'src/lib.rs', lines 146:4-149:5
    Visibility: public -/
structure server.StagedServerSession where
  prepare : wire.PrepareEnvelope
  y_relayer32_le : Array Std.U8 32#usize

/-- [ecdsa_hss::server::RespondResponse]
    Source: 'src/lib.rs', lines 152:4-155:5
    Visibility: public -/
structure server.RespondResponse where
  client_output : client.ClientOutput
  finalize : wire.FinalizeEnvelope

/-- [ecdsa_hss::server::boundary::VisibleOperationBoundary]
    Source: 'src/lib.rs', lines 167:8-170:9
    Visibility: public -/
structure server.boundary.VisibleOperationBoundary where
  operation : wire.ServerEvalOperation
  allowed_output_kind : wire.AllowedOutputKind

/-- [ecdsa_hss::server::boundary::VisibleNonExportBoundary]
    Source: 'src/lib.rs', lines 173:8-180:9
    Visibility: public -/
structure server.boundary.VisibleNonExportBoundary where
  client_public_key33 : Array Std.U8 33#usize
  relayer_public_key33 : Array Std.U8 33#usize
  threshold_public_key33 : Array Std.U8 33#usize
  threshold_ethereum_address20 : Array Std.U8 20#usize
  client_share_retry_counter : Std.U32
  relayer_share_retry_counter : Std.U32

/-- [ecdsa_hss::server::boundary::VisibleExplicitExportBoundary]
    Source: 'src/lib.rs', lines 183:8-191:9
    Visibility: public -/
structure server.boundary.VisibleExplicitExportBoundary where
  relayer_export_share32 : Array Std.U8 32#usize
  client_public_key33 : Array Std.U8 33#usize
  relayer_public_key33 : Array Std.U8 33#usize
  threshold_public_key33 : Array Std.U8 33#usize
  threshold_ethereum_address20 : Array Std.U8 20#usize
  client_share_retry_counter : Std.U32
  relayer_share_retry_counter : Std.U32

/-- [ecdsa_hss::server::boundary::VisibleClientBoundary]
    Source: 'src/lib.rs', lines 194:8-197:9
    Visibility: public -/
@[discriminant isize]
inductive server.boundary.VisibleClientBoundary where
| NonExport :
  server.boundary.VisibleNonExportBoundary →
  server.boundary.VisibleClientBoundary
| ExplicitExport :
  server.boundary.VisibleExplicitExportBoundary →
  server.boundary.VisibleClientBoundary

/-- [ecdsa_hss::server::boundary::VisibleFinalizeBoundary]
    Source: 'src/lib.rs', lines 200:8-211:9
    Visibility: public -/
structure server.boundary.VisibleFinalizeBoundary where
  operation : wire.ServerEvalOperation
  raw_root_material_dropped : Bool
  relayer_key_id : String
  context_binding32 : Array Std.U8 32#usize
  client_public_key33 : Array Std.U8 33#usize
  relayer_public_key33 : Array Std.U8 33#usize
  threshold_public_key33 : Array Std.U8 33#usize
  threshold_ethereum_address20 : Array Std.U8 20#usize
  client_share_retry_counter : Std.U32
  relayer_share_retry_counter : Std.U32

/-- [ecdsa_hss::server::boundary::VisibleRespondBoundary]
    Source: 'src/lib.rs', lines 227:8-231:9
    Visibility: public -/
structure server.boundary.VisibleRespondBoundary where
  operation : server.boundary.VisibleOperationBoundary
  client_output : server.boundary.VisibleClientBoundary
  finalize : server.boundary.VisibleFinalizeBoundary

/-- [ecdsa_hss::server::boundary::HiddenEvalInputBoundary]
    Source: 'src/lib.rs', lines 234:8-243:9
    Visibility: public -/
structure server.boundary.HiddenEvalInputBoundary where
  operation : wire.ServerEvalOperation
  allowed_output_kind : wire.AllowedOutputKind
  context : shared.context.EcdsaHssStableKeyContext
  relayer_key_id : String
  client_public_key33 : Array Std.U8 33#usize
  client_share_retry_counter : Std.U32
  expected_relayer_key_id : String
  y_relayer32_le : Array Std.U8 32#usize

/-- [ecdsa_hss::server::boundary::HiddenEvalTransportBoundary]
    Source: 'src/lib.rs', lines 246:8-250:9
    Visibility: public -/
structure server.boundary.HiddenEvalTransportBoundary where
  operation : server.boundary.VisibleOperationBoundary
  client_output : server.boundary.VisibleClientBoundary
  finalize : server.boundary.VisibleFinalizeBoundary

/-- [ecdsa_hss::server::boundary::HiddenEvalPersistedStateBoundary]
    Source: 'src/lib.rs', lines 253:8-264:9
    Visibility: public -/
structure server.boundary.HiddenEvalPersistedStateBoundary where
  operation : wire.ServerEvalOperation
  raw_root_material_dropped : Bool
  relayer_key_id : String
  relayer_share32 : Array Std.U8 32#usize
  client_public_key33 : Array Std.U8 33#usize
  relayer_public_key33 : Array Std.U8 33#usize
  threshold_public_key33 : Array Std.U8 33#usize
  threshold_ethereum_address20 : Array Std.U8 20#usize
  client_share_retry_counter : Std.U32
  relayer_share_retry_counter : Std.U32

/-- [ecdsa_hss::server::boundary::HiddenEvalBoundary]
    Source: 'src/lib.rs', lines 267:8-271:9
    Visibility: public -/
structure server.boundary.HiddenEvalBoundary where
  input : server.boundary.HiddenEvalInputBoundary
  transport : server.boundary.HiddenEvalTransportBoundary
  persisted : server.boundary.HiddenEvalPersistedStateBoundary

end ecdsa_hss
