#![cfg(all(feature = "threshold-ecdsa", feature = "typescript-bindings"))]

use std::{env, fs, path::PathBuf};

use signer_core::commands::{
    Base64UrlEncodingV1, BuildEcdsaRoleLocalExportArtifactCommandKindV1,
    BuildEcdsaRoleLocalExportArtifactCommandV1, BuildEcdsaRoleLocalExportArtifactErrorCodeV1,
    BuildEcdsaRoleLocalExportArtifactOutputV1, EcdsaBootstrapSecretSourceV1,
    EcdsaClientBootstrapAlgorithmV1, EcdsaClientBootstrapContextV1, EcdsaClientBootstrapFactsV1,
    EcdsaClientBootstrapParticipantsV1, EcdsaPreparePublicFactsV1, EcdsaReadyPublicFactsV1,
    EcdsaRoleLocalExportPublicFactsV1, EcdsaRoleLocalPendingStateBlobV1,
    EcdsaRoleLocalReadyStateBlobV1, Ed25519CreateClientPresignFromWorkerMaterialRequestKindV1,
    Ed25519CreateClientPresignFromWorkerMaterialRequestV1,
    Ed25519CreateClientPresignFromWorkerMaterialSuccessV1,
    Ed25519DeleteSealedWorkerMaterialRequestKindV1, Ed25519DeleteSealedWorkerMaterialRequestV1,
    Ed25519DeleteSealedWorkerMaterialSuccessV1, Ed25519HssClientOutputMaskTransportV1,
    Ed25519PutSealedWorkerMaterialRequestKindV1, Ed25519PutSealedWorkerMaterialRequestV1,
    Ed25519PutSealedWorkerMaterialSuccessV1, Ed25519ReadSealedWorkerMaterialRequestKindV1,
    Ed25519ReadSealedWorkerMaterialRequestV1, Ed25519ReadSealedWorkerMaterialSuccessV1,
    Ed25519RestoreWorkerMaterialRequestKindV1, Ed25519RestoreWorkerMaterialRequestV1,
    Ed25519SealedWorkerMaterialAadKindV1, Ed25519SealedWorkerMaterialAadV1,
    Ed25519SealedWorkerMaterialKindV1, Ed25519SealedWorkerMaterialTransportV1,
    Ed25519SealedWorkerMaterialV1, Ed25519ServerCommitmentsV1,
    Ed25519SignClientPresignFromWorkerMaterialRequestKindV1,
    Ed25519SignClientPresignFromWorkerMaterialRequestV1,
    Ed25519SignClientPresignFromWorkerMaterialSuccessV1,
    Ed25519StoreWorkerMaterialFromHssOutputRequestKindV1,
    Ed25519StoreWorkerMaterialFromHssOutputRequestV1, Ed25519ValidateWorkerMaterialRequestKindV1,
    Ed25519ValidateWorkerMaterialRequestV1, Ed25519ValidateWorkerMaterialSuccessV1,
    Ed25519WorkerMaterialAeadAlgorithmV1, Ed25519WorkerMaterialAeadV1,
    Ed25519WorkerMaterialBindingKindV1, Ed25519WorkerMaterialBindingV1,
    Ed25519WorkerMaterialCredentialAuthorizationPurposeV1,
    Ed25519WorkerMaterialCredentialAuthorizationV1, Ed25519WorkerMaterialCurveV1,
    Ed25519WorkerMaterialErrorCodeV1, Ed25519WorkerMaterialFailureV1,
    Ed25519WorkerMaterialFormatVersionV1, Ed25519WorkerMaterialKdfAlgorithmV1,
    Ed25519WorkerMaterialKdfV1, Ed25519WorkerMaterialKeyIdentityKindV1,
    Ed25519WorkerMaterialKeyIdentityV1, Ed25519WorkerMaterialProtocolV1,
    Ed25519WorkerMaterialSessionBindingKindV1, Ed25519WorkerMaterialSessionBindingV1,
    Ed25519WorkerMaterialStoredV1, FinalizeEcdsaClientBootstrapCommandKindV1,
    FinalizeEcdsaClientBootstrapCommandV1, FinalizeEcdsaClientBootstrapErrorCodeV1,
    FinalizeEcdsaClientBootstrapOutputV1, PendingStateBlobKindV1,
    PrepareEcdsaClientBootstrapCommandKindV1, PrepareEcdsaClientBootstrapCommandV1,
    PrepareEcdsaClientBootstrapErrorCodeV1, PrepareEcdsaClientBootstrapOutputV1,
    ReadyStateBlobKindV1, RelayerPublicIdentityV1, Secp256k1CurveNameV1, SignerCommandVersion,
    SignerCoreProducerV1, ThresholdRuntimePolicyScopeV1,
};
use ts_rs::{Config, TS};

const UPDATE_ENV: &str = "UPDATE_SIGNER_CORE_TYPES";
const GENERATED_HEADER: &str = concat!(
    "// This file was generated by `pnpm generate:signer-core-types`.\n",
    "// Do not edit this file manually.\n\n",
);

fn repo_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(|path| path.parent())
        .expect("signer-core crate is under crates/signer-core")
        .to_path_buf()
}

fn generated_schema_path() -> PathBuf {
    repo_root().join("packages/sdk-web/src/core/platform/generated/signerCoreCommands.ts")
}

fn push_decl<T: TS + 'static>(out: &mut String, cfg: &Config) {
    out.push_str("export ");
    out.push_str(&T::decl(cfg));
    out.push_str("\n\n");
}

fn generated_signer_core_commands_ts() -> String {
    let cfg = Config::new();
    let mut out = String::from(GENERATED_HEADER);

    push_decl::<SignerCommandVersion>(&mut out, &cfg);
    push_decl::<EcdsaBootstrapSecretSourceV1>(&mut out, &cfg);
    push_decl::<EcdsaClientBootstrapAlgorithmV1>(&mut out, &cfg);
    push_decl::<EcdsaClientBootstrapContextV1>(&mut out, &cfg);
    push_decl::<EcdsaClientBootstrapParticipantsV1>(&mut out, &cfg);
    push_decl::<PrepareEcdsaClientBootstrapCommandKindV1>(&mut out, &cfg);
    push_decl::<PrepareEcdsaClientBootstrapCommandV1>(&mut out, &cfg);
    push_decl::<PendingStateBlobKindV1>(&mut out, &cfg);
    push_decl::<ReadyStateBlobKindV1>(&mut out, &cfg);
    push_decl::<Secp256k1CurveNameV1>(&mut out, &cfg);
    push_decl::<Base64UrlEncodingV1>(&mut out, &cfg);
    push_decl::<SignerCoreProducerV1>(&mut out, &cfg);
    push_decl::<EcdsaRoleLocalPendingStateBlobV1>(&mut out, &cfg);
    push_decl::<EcdsaRoleLocalReadyStateBlobV1>(&mut out, &cfg);
    push_decl::<EcdsaClientBootstrapFactsV1>(&mut out, &cfg);
    push_decl::<EcdsaPreparePublicFactsV1>(&mut out, &cfg);
    push_decl::<PrepareEcdsaClientBootstrapOutputV1>(&mut out, &cfg);
    push_decl::<PrepareEcdsaClientBootstrapErrorCodeV1>(&mut out, &cfg);
    push_decl::<RelayerPublicIdentityV1>(&mut out, &cfg);
    push_decl::<FinalizeEcdsaClientBootstrapCommandKindV1>(&mut out, &cfg);
    push_decl::<FinalizeEcdsaClientBootstrapCommandV1>(&mut out, &cfg);
    push_decl::<EcdsaReadyPublicFactsV1>(&mut out, &cfg);
    push_decl::<FinalizeEcdsaClientBootstrapOutputV1>(&mut out, &cfg);
    push_decl::<FinalizeEcdsaClientBootstrapErrorCodeV1>(&mut out, &cfg);
    push_decl::<BuildEcdsaRoleLocalExportArtifactCommandKindV1>(&mut out, &cfg);
    push_decl::<EcdsaRoleLocalExportPublicFactsV1>(&mut out, &cfg);
    push_decl::<BuildEcdsaRoleLocalExportArtifactCommandV1>(&mut out, &cfg);
    push_decl::<BuildEcdsaRoleLocalExportArtifactOutputV1>(&mut out, &cfg);
    push_decl::<BuildEcdsaRoleLocalExportArtifactErrorCodeV1>(&mut out, &cfg);
    push_decl::<Ed25519WorkerMaterialFormatVersionV1>(&mut out, &cfg);
    push_decl::<Ed25519WorkerMaterialCurveV1>(&mut out, &cfg);
    push_decl::<Ed25519WorkerMaterialProtocolV1>(&mut out, &cfg);
    push_decl::<Ed25519WorkerMaterialAeadAlgorithmV1>(&mut out, &cfg);
    push_decl::<Ed25519WorkerMaterialKdfAlgorithmV1>(&mut out, &cfg);
    push_decl::<Ed25519WorkerMaterialKeyIdentityKindV1>(&mut out, &cfg);
    push_decl::<Ed25519WorkerMaterialBindingKindV1>(&mut out, &cfg);
    push_decl::<Ed25519WorkerMaterialSessionBindingKindV1>(&mut out, &cfg);
    push_decl::<Ed25519SealedWorkerMaterialKindV1>(&mut out, &cfg);
    push_decl::<Ed25519SealedWorkerMaterialAadKindV1>(&mut out, &cfg);
    push_decl::<Ed25519WorkerMaterialKeyIdentityV1>(&mut out, &cfg);
    push_decl::<Ed25519WorkerMaterialBindingV1>(&mut out, &cfg);
    push_decl::<ThresholdRuntimePolicyScopeV1>(&mut out, &cfg);
    push_decl::<Ed25519WorkerMaterialSessionBindingV1>(&mut out, &cfg);
    push_decl::<Ed25519WorkerMaterialAeadV1>(&mut out, &cfg);
    push_decl::<Ed25519WorkerMaterialKdfV1>(&mut out, &cfg);
    push_decl::<Ed25519SealedWorkerMaterialV1>(&mut out, &cfg);
    push_decl::<Ed25519SealedWorkerMaterialAadV1>(&mut out, &cfg);
    push_decl::<Ed25519SealedWorkerMaterialTransportV1>(&mut out, &cfg);
    push_decl::<Ed25519WorkerMaterialCredentialAuthorizationPurposeV1>(&mut out, &cfg);
    push_decl::<Ed25519WorkerMaterialCredentialAuthorizationV1>(&mut out, &cfg);
    push_decl::<Ed25519WorkerMaterialErrorCodeV1>(&mut out, &cfg);
    push_decl::<Ed25519WorkerMaterialFailureV1>(&mut out, &cfg);
    push_decl::<Ed25519WorkerMaterialStoredV1>(&mut out, &cfg);
    push_decl::<Ed25519ValidateWorkerMaterialSuccessV1>(&mut out, &cfg);
    push_decl::<Ed25519CreateClientPresignFromWorkerMaterialSuccessV1>(&mut out, &cfg);
    push_decl::<Ed25519SignClientPresignFromWorkerMaterialSuccessV1>(&mut out, &cfg);
    push_decl::<Ed25519StoreWorkerMaterialFromHssOutputRequestKindV1>(&mut out, &cfg);
    push_decl::<Ed25519HssClientOutputMaskTransportV1>(&mut out, &cfg);
    push_decl::<Ed25519StoreWorkerMaterialFromHssOutputRequestV1>(&mut out, &cfg);
    push_decl::<Ed25519RestoreWorkerMaterialRequestKindV1>(&mut out, &cfg);
    push_decl::<Ed25519RestoreWorkerMaterialRequestV1>(&mut out, &cfg);
    push_decl::<Ed25519ValidateWorkerMaterialRequestKindV1>(&mut out, &cfg);
    push_decl::<Ed25519ValidateWorkerMaterialRequestV1>(&mut out, &cfg);
    push_decl::<Ed25519CreateClientPresignFromWorkerMaterialRequestKindV1>(&mut out, &cfg);
    push_decl::<Ed25519CreateClientPresignFromWorkerMaterialRequestV1>(&mut out, &cfg);
    push_decl::<Ed25519ServerCommitmentsV1>(&mut out, &cfg);
    push_decl::<Ed25519SignClientPresignFromWorkerMaterialRequestKindV1>(&mut out, &cfg);
    push_decl::<Ed25519SignClientPresignFromWorkerMaterialRequestV1>(&mut out, &cfg);
    push_decl::<Ed25519PutSealedWorkerMaterialSuccessV1>(&mut out, &cfg);
    push_decl::<Ed25519ReadSealedWorkerMaterialSuccessV1>(&mut out, &cfg);
    push_decl::<Ed25519DeleteSealedWorkerMaterialSuccessV1>(&mut out, &cfg);
    push_decl::<Ed25519PutSealedWorkerMaterialRequestKindV1>(&mut out, &cfg);
    push_decl::<Ed25519PutSealedWorkerMaterialRequestV1>(&mut out, &cfg);
    push_decl::<Ed25519ReadSealedWorkerMaterialRequestKindV1>(&mut out, &cfg);
    push_decl::<Ed25519ReadSealedWorkerMaterialRequestV1>(&mut out, &cfg);
    push_decl::<Ed25519DeleteSealedWorkerMaterialRequestKindV1>(&mut out, &cfg);
    push_decl::<Ed25519DeleteSealedWorkerMaterialRequestV1>(&mut out, &cfg);

    out
}

#[test]
fn signer_core_typescript_schemas_are_current() {
    let generated = generated_signer_core_commands_ts();
    let path = generated_schema_path();

    if env::var(UPDATE_ENV).as_deref() == Ok("1") {
        fs::create_dir_all(path.parent().expect("generated file has parent directory"))
            .expect("create generated schema directory");
        fs::write(&path, generated).expect("write generated schema file");
        return;
    }

    let existing = fs::read_to_string(&path).unwrap_or_else(|error| {
        panic!(
            "failed to read generated signer-core schema file at {}: {error}",
            path.display()
        )
    });

    assert_eq!(
        existing, generated,
        "generated signer-core schemas are stale; run `pnpm generate:signer-core-types`"
    );
}
