import type { AuthService } from '../core/AuthService';

export type ThresholdRelayAuthService = Pick<AuthService, 'getThresholdSigningService'>;

export type CloudflareEmailAuthService = Pick<AuthService, 'emailRecovery'>;

export type CloudflareRelayAuthServiceMethod =
  | 'applyEmailOtpServerSeal'
  | 'cleanupGoogleEmailOtpDevRegistrationState'
  | 'consumeEmailOtpGrant'
  | 'consumeGoogleEmailOtpRegistrationAttemptRateLimit'
  | 'consumeEmailOtpRecoveryKey'
  | 'createAddAuthMethodIntent'
  | 'createAddSignerIntent'
  | 'createEmailOtpChallenge'
  | 'createEmailOtpDeviceRecoveryChallenge'
  | 'createEmailOtpEnrollmentChallenge'
  | 'createEmailOtpUnlockChallenge'
  | 'createRegistrationIntent'
  | 'createWebAuthnLoginOptions'
  | 'createWebAuthnSyncAccountOptions'
  | 'ecdsaHssRoleLocalBootstrap'
  | 'ecdsaHssRoleLocalExportShare'
  | 'executeSignedDelegate'
  | 'finalizeWalletAddAuthMethod'
  | 'finalizeWalletAddSigner'
  | 'finalizeWalletRegistration'
  | 'getConfiguredRelayerAccount'
  | 'getEmailOtpRecoveryCodeStatus'
  | 'getGoogleOidcPublicConfig'
  | 'getOrCreateAppSessionVersion'
  | 'getRecoverySession'
  | 'getRelayerAccount'
  | 'getThresholdSigningService'
  | 'isEmailOtpStrongAuthRequired'
  | 'linkIdentity'
  | 'listIdentities'
  | 'listNearPublicKeysForUser'
  | 'listThresholdEcdsaKeyIdentityTargetsForUser'
  | 'listWalletEcdsaKeyFactsInventory'
  | 'listWebAuthnAuthenticatorsForUser'
  | 'markEmailOtpStrongAuthSatisfied'
  | 'prepareEmailRecovery'
  | 'prepareWalletRegistration'
  | 'readActiveEmailOtpEnrollment'
  | 'readEmailOtpEnrollment'
  | 'readEmailOtpOutboxEntry'
  | 'recordEmailOtpRecoveryKeyAttemptFailure'
  | 'recordRecoveryExecution'
  | 'removeEmailOtpServerSeal'
  | 'respondWalletAddSignerHss'
  | 'respondWalletRegistrationHss'
  | 'resolveGoogleEmailOtpSession'
  | 'resolveOidcWalletId'
  | 'respondEmailRecoveryEcdsa'
  | 'revokeWalletAuthMethod'
  | 'rotateEmailOtpRecoveryKeys'
  | 'rotateAppSessionVersion'
  | 'startWalletAddAuthMethod'
  | 'startWalletAddSigner'
  | 'startWalletRegistration'
  | 'unlinkIdentity'
  | 'updateRecoverySessionStatus'
  | 'validateAppSessionVersion'
  | 'verifyEmailOtpChallenge'
  | 'verifyEmailOtpDeviceRecoveryChallenge'
  | 'verifyEmailOtpEnrollment'
  | 'verifyEmailOtpUnlockProof'
  | 'verifyEcdsaHssRoleLocalClientRootProofForExistingKey'
  | 'verifyGoogleLogin'
  | 'verifyOidcJwtExchange'
  | 'verifyWebAuthnAuthenticationLite'
  | 'verifyWebAuthnLogin'
  | 'verifyWebAuthnSyncAccount';

export type CloudflareRelayAuthService = CloudflareEmailAuthService &
  Pick<AuthService, CloudflareRelayAuthServiceMethod>;
