CREATE TABLE IF NOT EXISTS signing_root_secret_shares (
  namespace TEXT NOT NULL,
  org_id TEXT NOT NULL,
  project_id TEXT NOT NULL,
  env_id TEXT NOT NULL,
  signing_root_id TEXT NOT NULL,
  signing_root_version TEXT NOT NULL,
  share_id INTEGER NOT NULL,
  sealed_share_b64u TEXT NOT NULL,
  storage_id TEXT,
  kek_id TEXT NOT NULL,
  envelope_version TEXT NOT NULL,
  aad_digest_b64u TEXT NOT NULL,
  ciphertext_digest_b64u TEXT NOT NULL,
  rotation_state TEXT NOT NULL,
  rotated_from_kek_id TEXT,
  rotated_at_ms INTEGER,
  retired_at_ms INTEGER,
  last_audit_event_id TEXT NOT NULL,
  created_at_ms INTEGER NOT NULL,
  updated_at_ms INTEGER NOT NULL,
  PRIMARY KEY (
    namespace,
    org_id,
    project_id,
    env_id,
    signing_root_id,
    signing_root_version,
    share_id
  ),
  CHECK (length(namespace) > 0),
  CHECK (length(org_id) > 0),
  CHECK (length(project_id) > 0),
  CHECK (length(env_id) > 0),
  CHECK (length(signing_root_id) > 0),
  CHECK (share_id IN (1, 2, 3)),
  CHECK (length(sealed_share_b64u) > 0),
  CHECK (sealed_share_b64u NOT GLOB '*[^A-Za-z0-9_-]*'),
  CHECK (storage_id IS NULL OR length(storage_id) > 0),
  CHECK (length(kek_id) > 0),
  CHECK (length(envelope_version) > 0),
  CHECK (length(aad_digest_b64u) = 43),
  CHECK (aad_digest_b64u NOT GLOB '*[^A-Za-z0-9_-]*'),
  CHECK (length(ciphertext_digest_b64u) = 43),
  CHECK (ciphertext_digest_b64u NOT GLOB '*[^A-Za-z0-9_-]*'),
  CHECK (rotation_state IN ('active', 'rotation_pending', 'rotated', 'retired')),
  CHECK (rotated_from_kek_id IS NULL OR length(rotated_from_kek_id) > 0),
  CHECK (rotated_at_ms IS NULL OR rotated_at_ms >= created_at_ms),
  CHECK (retired_at_ms IS NULL OR retired_at_ms >= created_at_ms),
  CHECK (length(last_audit_event_id) > 0),
  CHECK (created_at_ms > 0),
  CHECK (updated_at_ms >= created_at_ms)
);

CREATE INDEX IF NOT EXISTS signing_root_secret_shares_scope_idx
  ON signing_root_secret_shares (
    namespace,
    org_id,
    project_id,
    env_id,
    signing_root_id,
    signing_root_version,
    share_id
  );
