import type {
  EcdsaLoginSessionSurface,
  EcdsaRegistrationSurface,
  Ed25519YaoRegistrationActivationSurface,
  EcdsaSessionBootstrapSurface,
  EcdsaSessionControlSurface,
  Ed25519SessionConnectionSurface,
  EmailOtpRegistrationEnrollmentSurface,
  EmailOtpSigningSessionSurface,
  EvmFamilySigningSurface,
  KeyExportSigningSurface,
  NearSigningSurface,
  NonceCoordinatorSurface,
  PasskeyLoginAssertionSurface,
  RegistrationAccountSurface,
  RpIdSurface,
  RuntimeStartupSurface,
  SeamsWebBaseContext,
  SignerWorkerContextSurface,
  SigningSessionSurface,
  TempoNonceLifecycleSurface,
  UserProfileStoreSurface,
  WarmSessionStatusSurface,
  WalletIframeWarmupSurface,
  WebAuthnRegistrationConfirmationSurface,
} from './ports';
import type { UserPreferencesManager } from '@/core/signingEngine/session/userPreferences';
import type { AppearanceConfig, SeamsConfigsReadonly } from '@/core/types/seams';
import type { WorkerOperationContext } from '@/core/signingEngine/workerManager/executeWorkerOperation';

export type {
  AccountSyncSigningSurface,
  AccountSyncWebContext,
  WalletAuthWebContext,
  DeviceLinkingSigningSurface,
  DeviceLinkingWebContext,
  EcdsaLoginSessionSurface,
  EcdsaRegistrationSurface,
  Ed25519YaoRegistrationActivationSurface,
  EcdsaSessionBootstrapSurface,
  EcdsaSessionControlSurface,
  Ed25519SessionConnectionSurface,
  EmailOtpRegistrationEnrollmentSurface,
  EmailOtpSigningSessionSurface,
  EmailRecoverySigningSurface,
  EmailRecoveryWebContext,
  EvmFamilySigningSurface,
  LocalLoginStateSurface,
  LocalLoginStateWebContext,
  LockSigningSurface,
  LockWebContext,
  LoginUnlockSigningSurface,
  LoginWarmSigningSurface,
  LoginWebContext,
  NearSigningSurface,
  NearSigningWebContext,
  NonceCoordinatorSurface,
  PasskeyLoginAssertionSurface,
  RecentUnlocksSigningSurface,
  RecentUnlocksWebContext,
  RegistrationAccountSurface,
  RegistrationSigningSurface,
  RegistrationWebContext,
  RpIdSurface,
  RuntimeStartupSurface,
  SeamsWebBaseContext,
  SignerWorkerContextSurface,
  SigningSessionSurface,
  TempoNonceLifecycleSurface,
  TempoSigningSurface,
  UserAccountLookupSurface,
  UserProfileStoreSurface,
  WalletIframeWarmupSurface,
  WalletSessionReadSurface,
  WalletSessionWebContext,
  WarmSessionStatusSurface,
  WebAuthnRegistrationConfirmationSurface,
} from './ports';

export type * from '../publicApi/types';

export interface SeamsWebSigningSurface
  extends
    RpIdSurface,
    NonceCoordinatorSurface,
    WalletIframeWarmupSurface,
    RuntimeStartupSurface,
    WorkerOperationContext,
    SigningSessionSurface,
    Ed25519SessionConnectionSurface,
    EcdsaSessionBootstrapSurface,
    EmailOtpSigningSessionSurface,
    EmailOtpRegistrationEnrollmentSurface,
    EcdsaLoginSessionSurface,
    EcdsaSessionControlSurface,
    SignerWorkerContextSurface,
    WarmSessionStatusSurface,
    NearSigningSurface,
    EvmFamilySigningSurface,
    TempoNonceLifecycleSurface,
    UserProfileStoreSurface,
    RegistrationAccountSurface,
    EcdsaRegistrationSurface,
    Ed25519YaoRegistrationActivationSurface,
    WebAuthnRegistrationConfirmationSurface,
    PasskeyLoginAssertionSurface,
    KeyExportSigningSurface {
  readonly seamsWebConfigs: SeamsConfigsReadonly;
  dispose(): void;
  setAppearance(appearance: AppearanceConfig): void;
  getUserPreferences(): UserPreferencesManager;
}

export type SeamsWebContext = SeamsWebBaseContext<SeamsWebSigningSurface>;
