/// Router replay Durable Object binding env key.
pub const ROUTER_REPLAY_DO_BINDING_ENV: &str = "ROUTER_REPLAY_DO_BINDING";
/// Router replay Durable Object object-name env key.
pub const ROUTER_REPLAY_DO_OBJECT_ENV: &str = "ROUTER_REPLAY_DO_OBJECT";
/// Router replay Durable Object key-prefix env key.
pub const ROUTER_REPLAY_DO_KEY_PREFIX_ENV: &str = "ROUTER_REPLAY_DO_KEY_PREFIX";
/// Router lifecycle Durable Object binding env key.
pub const ROUTER_LIFECYCLE_DO_BINDING_ENV: &str = "ROUTER_LIFECYCLE_DO_BINDING";
/// Router lifecycle Durable Object object-name env key.
pub const ROUTER_LIFECYCLE_DO_OBJECT_ENV: &str = "ROUTER_LIFECYCLE_DO_OBJECT";
/// Router lifecycle Durable Object key-prefix env key.
pub const ROUTER_LIFECYCLE_DO_KEY_PREFIX_ENV: &str = "ROUTER_LIFECYCLE_DO_KEY_PREFIX";
/// Router Wallet Session budget Durable Object binding env key.
pub const ROUTER_WALLET_BUDGET_DO_BINDING_ENV: &str = "ROUTER_WALLET_BUDGET_DO_BINDING";
/// Router Wallet Session budget Durable Object object-name env key.
pub const ROUTER_WALLET_BUDGET_DO_OBJECT_ENV: &str = "ROUTER_WALLET_BUDGET_DO_OBJECT";
/// Router Wallet Session budget Durable Object key-prefix env key.
pub const ROUTER_WALLET_BUDGET_DO_KEY_PREFIX_ENV: &str = "ROUTER_WALLET_BUDGET_DO_KEY_PREFIX";
/// Signer A root-share Durable Object binding env key.
pub const SIGNER_A_ROOT_SHARE_DO_BINDING_ENV: &str = "SIGNER_A_ROOT_SHARE_DO_BINDING";
/// Signer A root-share Durable Object object-name env key.
pub const SIGNER_A_ROOT_SHARE_DO_OBJECT_ENV: &str = "SIGNER_A_ROOT_SHARE_DO_OBJECT";
/// Signer A root-share Durable Object key-prefix env key.
pub const SIGNER_A_ROOT_SHARE_DO_KEY_PREFIX_ENV: &str = "SIGNER_A_ROOT_SHARE_DO_KEY_PREFIX";
/// SigningWorker server-output Durable Object binding env key.
pub const SIGNING_WORKER_SERVER_OUTPUT_DO_BINDING_ENV: &str =
    "SIGNING_WORKER_SERVER_OUTPUT_DO_BINDING";
/// SigningWorker server-output Durable Object object-name env key.
pub const SIGNING_WORKER_SERVER_OUTPUT_DO_OBJECT_ENV: &str =
    "SIGNING_WORKER_SERVER_OUTPUT_DO_OBJECT";
/// SigningWorker server-output Durable Object key-prefix env key.
pub const SIGNING_WORKER_SERVER_OUTPUT_DO_KEY_PREFIX_ENV: &str =
    "SIGNING_WORKER_SERVER_OUTPUT_DO_KEY_PREFIX";
/// SigningWorker server-output HPKE private-key binding-name env key.
pub const SIGNING_WORKER_SERVER_OUTPUT_HPKE_PRIVATE_KEY_BINDING_ENV: &str =
    "SIGNING_WORKER_SERVER_OUTPUT_HPKE_PRIVATE_KEY_BINDING";
/// SigningWorker server-output HPKE key epoch env key.
pub const SIGNING_WORKER_SERVER_OUTPUT_HPKE_KEY_EPOCH_ENV: &str =
    "SIGNING_WORKER_SERVER_OUTPUT_HPKE_KEY_EPOCH";
/// SigningWorker server-output HPKE public key env key.
pub const SIGNING_WORKER_SERVER_OUTPUT_HPKE_PUBLIC_KEY_ENV: &str =
    "SIGNING_WORKER_SERVER_OUTPUT_HPKE_PUBLIC_KEY";
/// Signer B root-share Durable Object binding env key.
pub const SIGNER_B_ROOT_SHARE_DO_BINDING_ENV: &str = "SIGNER_B_ROOT_SHARE_DO_BINDING";
/// Signer B root-share Durable Object object-name env key.
pub const SIGNER_B_ROOT_SHARE_DO_OBJECT_ENV: &str = "SIGNER_B_ROOT_SHARE_DO_OBJECT";
/// Signer B root-share Durable Object key-prefix env key.
pub const SIGNER_B_ROOT_SHARE_DO_KEY_PREFIX_ENV: &str = "SIGNER_B_ROOT_SHARE_DO_KEY_PREFIX";
/// Signer A signing-root-share wire Secret binding-name env key.
pub const SIGNER_A_ROOT_SHARE_WIRE_SECRET_BINDING_ENV: &str =
    "SIGNER_A_ROOT_SHARE_WIRE_SECRET_BINDING";
/// Signer B signing-root-share wire Secret binding-name env key.
pub const SIGNER_B_ROOT_SHARE_WIRE_SECRET_BINDING_ENV: &str =
    "SIGNER_B_ROOT_SHARE_WIRE_SECRET_BINDING";
/// Signer A peer binding env key.
pub const SIGNER_A_PEER_BINDING_ENV: &str = "SIGNER_A_PEER_BINDING";
/// Signer B peer binding env key.
pub const SIGNER_B_PEER_BINDING_ENV: &str = "SIGNER_B_PEER_BINDING";
/// SigningWorker peer binding env key.
pub const SIGNING_WORKER_PEER_BINDING_ENV: &str = "SIGNING_WORKER_PEER_BINDING";
/// Internal service-auth secret binding-name env key shared by strict private Workers.
pub const ROUTER_AB_INTERNAL_SERVICE_AUTH_SECRET_BINDING_ENV: &str =
    "ROUTER_AB_INTERNAL_SERVICE_AUTH_SECRET_BINDING";
/// Internal service-auth header required by strict private Workers.
pub const ROUTER_AB_INTERNAL_SERVICE_AUTH_HEADER_V1: &str = "x-router-ab-internal-service-auth";
/// Signer A signer-envelope HPKE private-key binding-name env key.
pub const SIGNER_A_ENVELOPE_HPKE_PRIVATE_KEY_BINDING_ENV: &str =
    "SIGNER_A_ENVELOPE_HPKE_PRIVATE_KEY_BINDING";
/// Signer A signer-envelope HPKE key epoch env key.
pub const SIGNER_A_ENVELOPE_HPKE_KEY_EPOCH_ENV: &str = "SIGNER_A_ENVELOPE_HPKE_KEY_EPOCH";
/// Signer A signer-envelope HPKE public key env key.
pub const SIGNER_A_ENVELOPE_HPKE_PUBLIC_KEY_ENV: &str = "SIGNER_A_ENVELOPE_HPKE_PUBLIC_KEY";
/// Previous Signer A signer-envelope HPKE key epoch env key.
pub const SIGNER_A_PREVIOUS_ENVELOPE_HPKE_KEY_EPOCH_ENV: &str =
    "SIGNER_A_PREVIOUS_ENVELOPE_HPKE_KEY_EPOCH";
/// Previous Signer A signer-envelope HPKE public key env key.
pub const SIGNER_A_PREVIOUS_ENVELOPE_HPKE_PUBLIC_KEY_ENV: &str =
    "SIGNER_A_PREVIOUS_ENVELOPE_HPKE_PUBLIC_KEY";
/// Previous Signer A signer-envelope HPKE private-key binding-name env key.
pub const SIGNER_A_PREVIOUS_ENVELOPE_HPKE_PRIVATE_KEY_BINDING_ENV: &str =
    "SIGNER_A_PREVIOUS_ENVELOPE_HPKE_PRIVATE_KEY_BINDING";
/// Signer B signer-envelope HPKE private-key binding-name env key.
pub const SIGNER_B_ENVELOPE_HPKE_PRIVATE_KEY_BINDING_ENV: &str =
    "SIGNER_B_ENVELOPE_HPKE_PRIVATE_KEY_BINDING";
/// Signer B signer-envelope HPKE key epoch env key.
pub const SIGNER_B_ENVELOPE_HPKE_KEY_EPOCH_ENV: &str = "SIGNER_B_ENVELOPE_HPKE_KEY_EPOCH";
/// Signer B signer-envelope HPKE public key env key.
pub const SIGNER_B_ENVELOPE_HPKE_PUBLIC_KEY_ENV: &str = "SIGNER_B_ENVELOPE_HPKE_PUBLIC_KEY";
/// Previous Signer B signer-envelope HPKE key epoch env key.
pub const SIGNER_B_PREVIOUS_ENVELOPE_HPKE_KEY_EPOCH_ENV: &str =
    "SIGNER_B_PREVIOUS_ENVELOPE_HPKE_KEY_EPOCH";
/// Previous Signer B signer-envelope HPKE public key env key.
pub const SIGNER_B_PREVIOUS_ENVELOPE_HPKE_PUBLIC_KEY_ENV: &str =
    "SIGNER_B_PREVIOUS_ENVELOPE_HPKE_PUBLIC_KEY";
/// Previous Signer B signer-envelope HPKE private-key binding-name env key.
pub const SIGNER_B_PREVIOUS_ENVELOPE_HPKE_PRIVATE_KEY_BINDING_ENV: &str =
    "SIGNER_B_PREVIOUS_ENVELOPE_HPKE_PRIVATE_KEY_BINDING";
/// Previous signer-envelope HPKE public-key retirement timestamp.
pub const ROUTER_AB_PREVIOUS_ENVELOPE_HPKE_RETIRE_AT_MS_ENV: &str =
    "ROUTER_AB_PREVIOUS_ENVELOPE_HPKE_RETIRE_AT_MS";
/// Signer A A/B peer-message Ed25519 signing secret binding-name env key.
pub const SIGNER_A_PEER_SIGNING_KEY_BINDING_ENV: &str = "SIGNER_A_PEER_SIGNING_KEY_BINDING";
/// Signer A A/B peer-message Ed25519 signing key epoch env key.
pub const SIGNER_A_PEER_SIGNING_KEY_EPOCH_ENV: &str = "SIGNER_A_PEER_SIGNING_KEY_EPOCH";
/// Signer B A/B peer-message Ed25519 signing secret binding-name env key.
pub const SIGNER_B_PEER_SIGNING_KEY_BINDING_ENV: &str = "SIGNER_B_PEER_SIGNING_KEY_BINDING";
/// Signer B A/B peer-message Ed25519 signing key epoch env key.
pub const SIGNER_B_PEER_SIGNING_KEY_EPOCH_ENV: &str = "SIGNER_B_PEER_SIGNING_KEY_EPOCH";
/// Signer A A/B peer-message Ed25519 verifying key env key.
pub const SIGNER_A_PEER_VERIFYING_KEY_HEX_ENV: &str = "SIGNER_A_PEER_VERIFYING_KEY_HEX";
/// Signer B A/B peer-message Ed25519 verifying key env key.
pub const SIGNER_B_PEER_VERIFYING_KEY_HEX_ENV: &str = "SIGNER_B_PEER_VERIFYING_KEY_HEX";
/// Router JWT issuer env key.
pub const ROUTER_JWT_ISSUER_ENV: &str = "ROUTER_JWT_ISSUER";
/// Router JWT audience env key.
pub const ROUTER_JWT_AUDIENCE_ENV: &str = "ROUTER_JWT_AUDIENCE";
/// Router JWKS URL env key.
pub const ROUTER_JWT_JWKS_URL_ENV: &str = "ROUTER_JWT_JWKS_URL";
/// Router project-policy Durable Object binding env key.
pub const ROUTER_PROJECT_POLICY_DO_BINDING_ENV: &str = "ROUTER_PROJECT_POLICY_DO_BINDING";
/// Router project-policy Durable Object object-name env key.
pub const ROUTER_PROJECT_POLICY_DO_OBJECT_ENV: &str = "ROUTER_PROJECT_POLICY_DO_OBJECT";
/// Router project-policy Durable Object key-prefix env key.
pub const ROUTER_PROJECT_POLICY_DO_KEY_PREFIX_ENV: &str = "ROUTER_PROJECT_POLICY_DO_KEY_PREFIX";
/// Router quota Durable Object binding env key.
pub const ROUTER_QUOTA_DO_BINDING_ENV: &str = "ROUTER_QUOTA_DO_BINDING";
/// Router quota Durable Object object-name env key.
pub const ROUTER_QUOTA_DO_OBJECT_ENV: &str = "ROUTER_QUOTA_DO_OBJECT";
/// Router quota Durable Object key-prefix env key.
pub const ROUTER_QUOTA_DO_KEY_PREFIX_ENV: &str = "ROUTER_QUOTA_DO_KEY_PREFIX";
/// Router abuse Durable Object binding env key.
pub const ROUTER_ABUSE_DO_BINDING_ENV: &str = "ROUTER_ABUSE_DO_BINDING";
/// Router abuse Durable Object object-name env key.
pub const ROUTER_ABUSE_DO_OBJECT_ENV: &str = "ROUTER_ABUSE_DO_OBJECT";
/// Router abuse Durable Object key-prefix env key.
pub const ROUTER_ABUSE_DO_KEY_PREFIX_ENV: &str = "ROUTER_ABUSE_DO_KEY_PREFIX";
/// Maximum random bytes a single signer-host preload may request.
pub const CLOUDFLARE_SIGNER_HOST_RANDOM_PRELOAD_MAX_BYTES_V1: usize = 65_536;
/// Versioned text prefix for a role-local MPC PRF signing-root-share wire secret.
pub const CLOUDFLARE_ROOT_SHARE_WIRE_SECRET_PREFIX_V1: &str = "mpc-prf-root-share-wire-v1:";
/// Versioned text prefix for a role-local signer-envelope HPKE private key.
pub const CLOUDFLARE_SIGNER_ENVELOPE_HPKE_PRIVATE_KEY_SECRET_PREFIX_V1: &str =
    "hpke-x25519-private-v1:";
/// Versioned text prefix for SigningWorker's server-output HPKE private key.
pub const CLOUDFLARE_SERVER_OUTPUT_HPKE_PRIVATE_KEY_SECRET_PREFIX_V1: &str =
    "hpke-x25519-server-output-private-v1:";

pub(crate) const ROUTER_FORBIDDEN_ENV_KEYS: &[&str] = &[
    SIGNER_A_ROOT_SHARE_DO_BINDING_ENV,
    SIGNER_A_ROOT_SHARE_DO_OBJECT_ENV,
    SIGNER_A_ROOT_SHARE_DO_KEY_PREFIX_ENV,
    SIGNING_WORKER_SERVER_OUTPUT_DO_BINDING_ENV,
    SIGNING_WORKER_SERVER_OUTPUT_DO_OBJECT_ENV,
    SIGNING_WORKER_SERVER_OUTPUT_DO_KEY_PREFIX_ENV,
    SIGNING_WORKER_SERVER_OUTPUT_HPKE_PRIVATE_KEY_BINDING_ENV,
    SIGNER_B_ROOT_SHARE_DO_BINDING_ENV,
    SIGNER_B_ROOT_SHARE_DO_OBJECT_ENV,
    SIGNER_B_ROOT_SHARE_DO_KEY_PREFIX_ENV,
    SIGNER_A_ROOT_SHARE_WIRE_SECRET_BINDING_ENV,
    SIGNER_B_ROOT_SHARE_WIRE_SECRET_BINDING_ENV,
    SIGNER_A_ENVELOPE_HPKE_PRIVATE_KEY_BINDING_ENV,
    SIGNER_A_PREVIOUS_ENVELOPE_HPKE_PRIVATE_KEY_BINDING_ENV,
    SIGNER_B_ENVELOPE_HPKE_PRIVATE_KEY_BINDING_ENV,
    SIGNER_B_PREVIOUS_ENVELOPE_HPKE_PRIVATE_KEY_BINDING_ENV,
    SIGNER_A_PEER_SIGNING_KEY_BINDING_ENV,
    SIGNER_A_PEER_SIGNING_KEY_EPOCH_ENV,
    SIGNER_B_PEER_SIGNING_KEY_BINDING_ENV,
    SIGNER_B_PEER_SIGNING_KEY_EPOCH_ENV,
];
pub(crate) const SIGNER_A_FORBIDDEN_ENV_KEYS: &[&str] = &[
    ROUTER_REPLAY_DO_BINDING_ENV,
    ROUTER_REPLAY_DO_OBJECT_ENV,
    ROUTER_REPLAY_DO_KEY_PREFIX_ENV,
    ROUTER_LIFECYCLE_DO_BINDING_ENV,
    ROUTER_LIFECYCLE_DO_OBJECT_ENV,
    ROUTER_LIFECYCLE_DO_KEY_PREFIX_ENV,
    ROUTER_WALLET_BUDGET_DO_BINDING_ENV,
    ROUTER_WALLET_BUDGET_DO_OBJECT_ENV,
    ROUTER_WALLET_BUDGET_DO_KEY_PREFIX_ENV,
    ROUTER_JWT_ISSUER_ENV,
    ROUTER_JWT_AUDIENCE_ENV,
    ROUTER_JWT_JWKS_URL_ENV,
    ROUTER_PROJECT_POLICY_DO_BINDING_ENV,
    ROUTER_PROJECT_POLICY_DO_OBJECT_ENV,
    ROUTER_PROJECT_POLICY_DO_KEY_PREFIX_ENV,
    ROUTER_QUOTA_DO_BINDING_ENV,
    ROUTER_QUOTA_DO_OBJECT_ENV,
    ROUTER_QUOTA_DO_KEY_PREFIX_ENV,
    ROUTER_ABUSE_DO_BINDING_ENV,
    ROUTER_ABUSE_DO_OBJECT_ENV,
    ROUTER_ABUSE_DO_KEY_PREFIX_ENV,
    SIGNER_B_ROOT_SHARE_DO_BINDING_ENV,
    SIGNER_B_ROOT_SHARE_DO_OBJECT_ENV,
    SIGNER_B_ROOT_SHARE_DO_KEY_PREFIX_ENV,
    SIGNER_B_ROOT_SHARE_WIRE_SECRET_BINDING_ENV,
    SIGNER_B_ENVELOPE_HPKE_PRIVATE_KEY_BINDING_ENV,
    SIGNER_B_PREVIOUS_ENVELOPE_HPKE_PRIVATE_KEY_BINDING_ENV,
    SIGNER_B_PEER_SIGNING_KEY_BINDING_ENV,
    SIGNER_B_PEER_SIGNING_KEY_EPOCH_ENV,
    SIGNING_WORKER_SERVER_OUTPUT_DO_BINDING_ENV,
    SIGNING_WORKER_SERVER_OUTPUT_DO_OBJECT_ENV,
    SIGNING_WORKER_SERVER_OUTPUT_DO_KEY_PREFIX_ENV,
    SIGNING_WORKER_SERVER_OUTPUT_HPKE_PRIVATE_KEY_BINDING_ENV,
];
pub(crate) const SIGNER_B_FORBIDDEN_ENV_KEYS: &[&str] = &[
    ROUTER_REPLAY_DO_BINDING_ENV,
    ROUTER_REPLAY_DO_OBJECT_ENV,
    ROUTER_REPLAY_DO_KEY_PREFIX_ENV,
    ROUTER_LIFECYCLE_DO_BINDING_ENV,
    ROUTER_LIFECYCLE_DO_OBJECT_ENV,
    ROUTER_LIFECYCLE_DO_KEY_PREFIX_ENV,
    ROUTER_WALLET_BUDGET_DO_BINDING_ENV,
    ROUTER_WALLET_BUDGET_DO_OBJECT_ENV,
    ROUTER_WALLET_BUDGET_DO_KEY_PREFIX_ENV,
    ROUTER_JWT_ISSUER_ENV,
    ROUTER_JWT_AUDIENCE_ENV,
    ROUTER_JWT_JWKS_URL_ENV,
    ROUTER_PROJECT_POLICY_DO_BINDING_ENV,
    ROUTER_PROJECT_POLICY_DO_OBJECT_ENV,
    ROUTER_PROJECT_POLICY_DO_KEY_PREFIX_ENV,
    ROUTER_QUOTA_DO_BINDING_ENV,
    ROUTER_QUOTA_DO_OBJECT_ENV,
    ROUTER_QUOTA_DO_KEY_PREFIX_ENV,
    ROUTER_ABUSE_DO_BINDING_ENV,
    ROUTER_ABUSE_DO_OBJECT_ENV,
    ROUTER_ABUSE_DO_KEY_PREFIX_ENV,
    SIGNER_A_ROOT_SHARE_DO_BINDING_ENV,
    SIGNER_A_ROOT_SHARE_DO_OBJECT_ENV,
    SIGNER_A_ROOT_SHARE_DO_KEY_PREFIX_ENV,
    SIGNER_A_ROOT_SHARE_WIRE_SECRET_BINDING_ENV,
    SIGNING_WORKER_SERVER_OUTPUT_DO_BINDING_ENV,
    SIGNING_WORKER_SERVER_OUTPUT_DO_OBJECT_ENV,
    SIGNING_WORKER_SERVER_OUTPUT_DO_KEY_PREFIX_ENV,
    SIGNING_WORKER_SERVER_OUTPUT_HPKE_PRIVATE_KEY_BINDING_ENV,
    SIGNER_A_ENVELOPE_HPKE_PRIVATE_KEY_BINDING_ENV,
    SIGNER_A_PREVIOUS_ENVELOPE_HPKE_PRIVATE_KEY_BINDING_ENV,
    SIGNER_A_PEER_SIGNING_KEY_BINDING_ENV,
    SIGNER_A_PEER_SIGNING_KEY_EPOCH_ENV,
];
pub(crate) const SIGNING_WORKER_FORBIDDEN_ENV_KEYS: &[&str] = &[
    ROUTER_REPLAY_DO_BINDING_ENV,
    ROUTER_REPLAY_DO_OBJECT_ENV,
    ROUTER_REPLAY_DO_KEY_PREFIX_ENV,
    ROUTER_LIFECYCLE_DO_BINDING_ENV,
    ROUTER_LIFECYCLE_DO_OBJECT_ENV,
    ROUTER_LIFECYCLE_DO_KEY_PREFIX_ENV,
    ROUTER_WALLET_BUDGET_DO_BINDING_ENV,
    ROUTER_WALLET_BUDGET_DO_OBJECT_ENV,
    ROUTER_WALLET_BUDGET_DO_KEY_PREFIX_ENV,
    ROUTER_JWT_ISSUER_ENV,
    ROUTER_JWT_AUDIENCE_ENV,
    ROUTER_JWT_JWKS_URL_ENV,
    ROUTER_PROJECT_POLICY_DO_BINDING_ENV,
    ROUTER_PROJECT_POLICY_DO_OBJECT_ENV,
    ROUTER_PROJECT_POLICY_DO_KEY_PREFIX_ENV,
    ROUTER_QUOTA_DO_BINDING_ENV,
    ROUTER_QUOTA_DO_OBJECT_ENV,
    ROUTER_QUOTA_DO_KEY_PREFIX_ENV,
    ROUTER_ABUSE_DO_BINDING_ENV,
    ROUTER_ABUSE_DO_OBJECT_ENV,
    ROUTER_ABUSE_DO_KEY_PREFIX_ENV,
    SIGNER_A_ROOT_SHARE_DO_BINDING_ENV,
    SIGNER_A_ROOT_SHARE_DO_OBJECT_ENV,
    SIGNER_A_ROOT_SHARE_DO_KEY_PREFIX_ENV,
    SIGNER_A_ROOT_SHARE_WIRE_SECRET_BINDING_ENV,
    SIGNER_A_ENVELOPE_HPKE_PRIVATE_KEY_BINDING_ENV,
    SIGNER_A_PREVIOUS_ENVELOPE_HPKE_PRIVATE_KEY_BINDING_ENV,
    SIGNER_A_PEER_SIGNING_KEY_BINDING_ENV,
    SIGNER_A_PEER_SIGNING_KEY_EPOCH_ENV,
    SIGNER_B_ROOT_SHARE_DO_BINDING_ENV,
    SIGNER_B_ROOT_SHARE_DO_OBJECT_ENV,
    SIGNER_B_ROOT_SHARE_DO_KEY_PREFIX_ENV,
    SIGNER_B_ROOT_SHARE_WIRE_SECRET_BINDING_ENV,
    SIGNER_B_ENVELOPE_HPKE_PRIVATE_KEY_BINDING_ENV,
    SIGNER_B_PREVIOUS_ENVELOPE_HPKE_PRIVATE_KEY_BINDING_ENV,
    SIGNER_B_PEER_SIGNING_KEY_BINDING_ENV,
    SIGNER_B_PEER_SIGNING_KEY_EPOCH_ENV,
];
