import { readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { expect, test } from '@playwright/test';
import {
  buildWalletCustodyRegistrationRecords,
  type WalletCustodyCeremonyCommitPayload,
} from '../../packages/wallet-server/src/router/domains/passkeyCustody/walletCustodyRegistrationCommit';
import {
  buildEmailOtpEnvelopeFactor,
  buildPasskeyEnvelopeFactor,
  buildWalletCustodySeedBinding,
  parsePasskeyCustodySecretBinding,
  parseWalletCustodyEnvelopeFactor,
} from '../../packages/shared-ts/src/passkey-custody';

/**
 * The TypeScript half of the wallet-custody wire contract.
 *
 * The fixture is generated by Rust from the production types and seal
 * functions (`wasm/wallet_custody_ceremony/tests/wire_fixtures.rs`), and Rust
 * asserts it byte-for-byte on every run. This suite parses the same file
 * through the TypeScript production parsers and rebuilds the bindings through
 * the TypeScript production builders — so a shape either side stops speaking
 * fails that side's suite, instead of shipping and failing at runtime the way
 * the seed-binding drift did.
 *
 * Regenerate only for an intended wire change, and never by hand:
 * `UPDATE_WALLET_CUSTODY_WIRE_FIXTURES=1 cargo test --test wire_fixtures`
 * (run in wasm/wallet_custody_ceremony).
 */

type FixtureDoc = {
  fixtureVersion: string;
  inputs: {
    walletId: string;
    envelopeId: string;
    enrollmentId: string;
    enrollmentSealKeyVersion: string;
    rpId: string;
    credentialIdB64u: string;
    recoveryCodes: readonly { recoveryKeyId: string; codeBytesB64u: string }[];
  };
  establishCommitPayload: WalletCustodyCeremonyCommitPayload;
  joinCommitPayload: WalletCustodyCeremonyCommitPayload;
  passkeyEnvelopeBinding: Record<string, unknown>;
  joinCustody: Record<string, unknown>;
};

function fixture(): FixtureDoc {
  const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
  const raw = readFileSync(
    path.join(repoRoot, 'wasm', 'wallet_custody_ceremony', 'fixtures', 'wallet-custody-wire-v1.json'),
    'utf8',
  );
  const doc = JSON.parse(raw) as FixtureDoc;
  expect(doc.fixtureVersion).toBe('wallet_custody_wire_v1');
  return doc;
}

function browserCommitPayload(
  payload: WalletCustodyCeremonyCommitPayload,
): WalletCustodyCeremonyCommitPayload {
  // Rust emits the pre-acknowledgement payload. The browser adds this marker
  // after the user visibly confirms the recovery backup before calling the
  // server adapter.
  return { ...payload, recoveryBackupAcknowledged: true };
}

const NOW_MS = 1_700_000_000_000;

test('the Rust establish payload parses into records through the production adapter', () => {
  const doc = fixture();
  const custody = doc.establishCommitPayload.establishedCustody;
  expect(custody).toBeTruthy();

  const records = buildWalletCustodyRegistrationRecords({
    payload: browserCommitPayload(doc.establishCommitPayload),
    factor: buildEmailOtpEnvelopeFactor({
      enrollmentId: doc.inputs.enrollmentId,
      enrollmentSealKeyVersion: doc.inputs.enrollmentSealKeyVersion,
    }),
    nowMs: NOW_MS,
  });

  expect(String(records.envelope.walletId)).toBe(doc.inputs.walletId);
  expect(String(records.envelope.envelopeId)).toBe(doc.inputs.envelopeId);
  expect(records.envelope.sealedCustodySecretB64u).toBe(custody!.sealedCustodySecretB64u);
  expect(records.envelope.aadHashB64u).toBe(custody!.envelopeAadHashB64u);
  expect(records.recoverySet.manifestKekWraps.map((wrap) => String(wrap.recoveryKeyId))).toEqual(
    doc.inputs.recoveryCodes.map((code) => code.recoveryKeyId),
  );
  expect(records.recoverySet.entries).toHaveLength(1);
});

test('the Rust join payload is refused: a joining run commits no custody records', () => {
  const doc = fixture();
  expect(() =>
    buildWalletCustodyRegistrationRecords({
      payload: browserCommitPayload(doc.joinCommitPayload),
      factor: buildEmailOtpEnvelopeFactor({
        enrollmentId: doc.inputs.enrollmentId,
        enrollmentSealKeyVersion: doc.inputs.enrollmentSealKeyVersion,
      }),
      nowMs: NOW_MS,
    }),
  ).toThrow(/joined existing custody/u);
});

test('the TypeScript builders reproduce the Rust envelope bindings byte-for-byte', () => {
  const doc = fixture();
  const custody = doc.establishCommitPayload.establishedCustody;

  // The direction that shipped broken once: TypeScript-built bindings must be
  // exactly what the Rust deny-unknown-fields parser accepts. The fixture's
  // binding IS that accepted form, so deep equality here closes the loop.
  const builtEmailOtp = {
    walletId: doc.inputs.walletId,
    envelopeId: doc.inputs.envelopeId,
    factor: buildEmailOtpEnvelopeFactor({
      enrollmentId: doc.inputs.enrollmentId,
      enrollmentSealKeyVersion: doc.inputs.enrollmentSealKeyVersion,
    }),
    envelopeRevision: 1,
    binding: buildWalletCustodySeedBinding(),
  };
  expect(builtEmailOtp).toEqual(JSON.parse(custody!.envelopeBindingJson));

  const builtPasskey = {
    walletId: doc.inputs.walletId,
    envelopeId: doc.inputs.envelopeId,
    factor: buildPasskeyEnvelopeFactor({
      rpId: doc.inputs.rpId,
      credentialIdB64u: doc.inputs.credentialIdB64u,
    } as Parameters<typeof buildPasskeyEnvelopeFactor>[0]),
    envelopeRevision: 1,
    binding: buildWalletCustodySeedBinding(),
  };
  expect(builtPasskey).toEqual(doc.passkeyEnvelopeBinding);
});

test('the shared parsers accept both fixture binding variants', () => {
  const doc = fixture();
  const emailOtpBinding = JSON.parse(
    doc.establishCommitPayload.establishedCustody!.envelopeBindingJson,
  ) as Record<string, unknown>;

  for (const [label, binding] of [
    ['emailOtp', emailOtpBinding],
    ['passkey', doc.passkeyEnvelopeBinding],
  ] as const) {
    const factor = parseWalletCustodyEnvelopeFactor(binding.factor, `${label}.factor`);
    expect(factor.kind).toBe(label === 'emailOtp' ? 'email_otp' : 'passkey');
    const secretBinding = parsePasskeyCustodySecretBinding(binding.binding, `${label}.binding`);
    expect(secretBinding.kind).toBe('wallet_custody_seed_v1');
  }
});

test('the join-custody wire carries exactly the fields the wasm boundary parses', () => {
  // JoinCustodyWireV1 uses deny_unknown_fields: an extra key is a rejection and
  // a missing one is too, so the key set itself is the contract. The Rust side
  // asserts this same section parses; this pins what the client must build.
  expect(Object.keys(fixture().joinCustody).sort()).toEqual([
    'aadHashB64u',
    'ciphertextDigestB64u',
    'envelopeBinding',
    'nonceB64u',
    'sealedCustodySecretB64u',
  ]);
});
